In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import os
from pathlib import Path
data_dir = Path("/content/drive/My Drive/Build1_DataPack")
os.listdir(data_dir)

['datapack']

In [4]:
import pandas as pd
df_results_pune_2026_06=pd.read_csv(data_dir / "datapack/results/pune/results_2026-06.csv.gz")
df_results_pune_2026_05=pd.read_csv(data_dir / "datapack/results/pune/results_2026-05.csv.gz")
df_results_pune_2026_04=pd.read_csv(data_dir / "datapack/results/pune/results_2026-04.csv.gz")
df_results_pune_2026_03=pd.read_csv(data_dir / "datapack/results/pune/results_2026-03.csv.gz")
df_results_pune_2026_02=pd.read_csv(data_dir / "datapack/results/pune/results_2026-02.csv.gz")
df_results_pune_2026_01=pd.read_csv(data_dir / "datapack/results/pune/results_2026-01.csv.gz")
display(df_results_pune_2026_06.shape,df_results_pune_2026_05.shape,df_results_pune_2026_04.shape,df_results_pune_2026_03.shape,df_results_pune_2026_02.shape,df_results_pune_2026_01.shape)
df_results_pune_2026_H1 = pd.concat([df_results_pune_2026_06, df_results_pune_2026_05, df_results_pune_2026_04, df_results_pune_2026_03, df_results_pune_2026_02, df_results_pune_2026_01])
df_results_pune_2026_H1.shape
df_results_jaipur_2026_06=pd.read_csv(data_dir / "datapack/results/jaipur/results_2026-06.csv.gz")
df_results_jaipur_2026_05=pd.read_csv(data_dir / "datapack/results/jaipur/results_2026-05.csv.gz")
df_results_jaipur_2026_04=pd.read_csv(data_dir / "datapack/results/jaipur/results_2026-04.csv.gz")
df_results_jaipur_2026_03=pd.read_csv(data_dir / "datapack/results/jaipur/results_2026-03.csv.gz")
df_results_jaipur_2026_02=pd.read_csv(data_dir / "datapack/results/jaipur/results_2026-02.csv.gz")
df_results_jaipur_2026_01=pd.read_csv(data_dir / "datapack/results/jaipur/results_2026-01.csv.gz")
display(df_results_jaipur_2026_06.shape,df_results_jaipur_2026_05.shape,df_results_jaipur_2026_04.shape,df_results_jaipur_2026_03.shape,df_results_jaipur_2026_02.shape,df_results_jaipur_2026_01.shape)
df_results_jaipur_2026_H1 = pd.concat([df_results_jaipur_2026_06, df_results_jaipur_2026_05, df_results_jaipur_2026_04, df_results_jaipur_2026_03, df_results_jaipur_2026_02, df_results_jaipur_2026_01])
df_results_jaipur_2026_H1.shape
df_results_hyderabad_2026_06=pd.read_csv(data_dir / "datapack/results/hyderabad/results_2026-06.csv.gz")
df_results_hyderabad_2026_05=pd.read_csv(data_dir / "datapack/results/hyderabad/results_2026-05.csv.gz")
df_results_hyderabad_2026_04=pd.read_csv(data_dir / "datapack/results/hyderabad/results_2026-04.csv.gz")
df_results_hyderabad_2026_03=pd.read_csv(data_dir / "datapack/results/hyderabad/results_2026-03.csv.gz")
df_results_hyderabad_2026_02=pd.read_csv(data_dir / "datapack/results/hyderabad/results_2026-02.csv.gz")
df_results_hyderabad_2026_01=pd.read_csv(data_dir / "datapack/results/hyderabad/results_2026-01.csv.gz")
display(df_results_hyderabad_2026_06.shape,df_results_hyderabad_2026_05.shape,df_results_hyderabad_2026_04.shape,df_results_hyderabad_2026_03.shape,df_results_hyderabad_2026_02.shape,df_results_hyderabad_2026_01.shape)
df_results_hyderabad_2026_H1 = pd.concat([df_results_hyderabad_2026_06, df_results_hyderabad_2026_05, df_results_hyderabad_2026_04, df_results_hyderabad_2026_03, df_results_hyderabad_2026_02, df_results_hyderabad_2026_01])
df_results_hyderabad_2026_H1.shape
df_results_chennai_2026_06=pd.read_csv(data_dir / "datapack/results/chennai/results_2026-06.csv.gz")
df_results_chennai_2026_05=pd.read_csv(data_dir / "datapack/results/chennai/results_2026-05.csv.gz")
df_results_chennai_2026_04=pd.read_csv(data_dir / "datapack/results/chennai/results_2026-04.csv.gz")
df_results_chennai_2026_03=pd.read_csv(data_dir / "datapack/results/chennai/results_2026-03.csv.gz")
df_results_chennai_2026_02=pd.read_csv(data_dir / "datapack/results/chennai/results_2026-02.csv.gz")
df_results_chennai_2026_01=pd.read_csv(data_dir / "datapack/results/chennai/results_2026-01.csv.gz")
display(df_results_chennai_2026_06.shape,df_results_chennai_2026_05.shape,df_results_chennai_2026_04.shape,df_results_chennai_2026_03.shape,df_results_chennai_2026_02.shape,df_results_chennai_2026_01.shape)
df_results_chennai_2026_H1 = pd.concat([df_results_chennai_2026_06, df_results_chennai_2026_05, df_results_chennai_2026_04, df_results_chennai_2026_03, df_results_chennai_2026_02, df_results_chennai_2026_01])
df_results_chennai_2026_H1.shape
df_results_bengaluru_2026_06=pd.read_csv(data_dir / "datapack/results/bengaluru/results_2026-06.csv.gz")
df_results_bengaluru_2026_05=pd.read_csv(data_dir / "datapack/results/bengaluru/results_2026-05.csv.gz")
df_results_bengaluru_2026_04=pd.read_csv(data_dir / "datapack/results/bengaluru/results_2026-04.csv.gz")
df_results_bengaluru_2026_03=pd.read_csv(data_dir / "datapack/results/bengaluru/results_2026-03.csv.gz")
df_results_bengaluru_2026_02=pd.read_csv(data_dir / "datapack/results/bengaluru/results_2026-02.csv.gz")
df_results_bengaluru_2026_01=pd.read_csv(data_dir / "datapack/results/bengaluru/results_2026-01.csv.gz")
display(df_results_bengaluru_2026_06.shape,df_results_bengaluru_2026_05.shape,df_results_bengaluru_2026_04.shape,df_results_bengaluru_2026_03.shape,df_results_bengaluru_2026_02.shape,df_results_bengaluru_2026_01.shape)
df_results_bengaluru_2026_H1 = pd.concat([df_results_bengaluru_2026_06, df_results_bengaluru_2026_05, df_results_bengaluru_2026_04, df_results_bengaluru_2026_03, df_results_bengaluru_2026_02, df_results_bengaluru_2026_01])
df_results_ahmedabad_2026_06=pd.read_csv(data_dir / "datapack/results/ahmedabad/results_2026-06.csv.gz")
df_results_ahmedabad_2026_05=pd.read_csv(data_dir / "datapack/results/ahmedabad/results_2026-05.csv.gz")
df_results_ahmedabad_2026_04=pd.read_csv(data_dir / "datapack/results/ahmedabad/results_2026-04.csv.gz")
df_results_ahmedabad_2026_03=pd.read_csv(data_dir / "datapack/results/ahmedabad/results_2026-03.csv.gz")
df_results_ahmedabad_2026_02=pd.read_csv(data_dir / "datapack/results/ahmedabad/results_2026-02.csv.gz")
df_results_ahmedabad_2026_01=pd.read_csv(data_dir / "datapack/results/ahmedabad/results_2026-01.csv.gz")
display(df_results_ahmedabad_2026_06.shape,df_results_ahmedabad_2026_05.shape,df_results_ahmedabad_2026_04.shape,df_results_ahmedabad_2026_03.shape,df_results_ahmedabad_2026_02.shape,df_results_ahmedabad_2026_01.shape)
df_results_ahmedabad_2026_H1 = pd.concat([df_results_ahmedabad_2026_06, df_results_ahmedabad_2026_05, df_results_ahmedabad_2026_04, df_results_ahmedabad_2026_03, df_results_ahmedabad_2026_02, df_results_ahmedabad_2026_01])

(8838, 5)

(8164, 5)

(9030, 5)

(9574, 5)

(9007, 5)

(9583, 5)

(5595, 5)

(5394, 5)

(5336, 5)

(5732, 5)

(5720, 5)

(5662, 5)

(10780, 5)

(10144, 5)

(10784, 5)

(10942, 5)

(11426, 5)

(10945, 5)

(10592, 5)

(10715, 5)

(10727, 5)

(10969, 5)

(12151, 5)

(11320, 5)

(13903, 5)

(14583, 5)

(14679, 5)

(14511, 5)

(16310, 5)

(15143, 5)

(11670, 5)

(11477, 5)

(11353, 5)

(11909, 5)

(12005, 5)

(11685, 5)

In [5]:
df_results_2026_H1 = pd.concat([df_results_pune_2026_H1,df_results_jaipur_2026_H1,df_results_hyderabad_2026_H1,df_results_chennai_2026_H1,df_results_bengaluru_2026_H1,df_results_ahmedabad_2026_H1])

In [6]:
df_results_2026_H1.shape

(378358, 5)

In [7]:
df_results_2026_H1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 378358 entries, 0 to 11684
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   booking_id    378358 non-null  object
 1   test_code     377209 non-null  object
 2   result_ts     378358 non-null  object
 3   result_value  378358 non-null  object
 4   result_flag   378358 non-null  object
dtypes: object(5)
memory usage: 17.3+ MB

In [8]:
import pandas as pd
df_results_pune_2025_06=pd.read_csv(data_dir / "datapack/results/pune/results_2025-06.csv.gz")
df_results_pune_2025_05=pd.read_csv(data_dir / "datapack/results/pune/results_2025-05.csv.gz")
df_results_pune_2025_04=pd.read_csv(data_dir / "datapack/results/pune/results_2025-04.csv.gz")
df_results_pune_2025_03=pd.read_csv(data_dir / "datapack/results/pune/results_2025-03.csv.gz")
df_results_pune_2025_02=pd.read_csv(data_dir / "datapack/results/pune/results_2025-02.csv.gz")
df_results_pune_2025_01=pd.read_csv(data_dir / "datapack/results/pune/results_2025-01.csv.gz")
display(df_results_pune_2025_06.shape,df_results_pune_2025_05.shape,df_results_pune_2025_04.shape,df_results_pune_2025_03.shape,df_results_pune_2025_02.shape,df_results_pune_2025_01.shape)
df_results_pune_2025_H1 = pd.concat([df_results_pune_2025_06, df_results_pune_2025_05, df_results_pune_2025_04, df_results_pune_2025_03, df_results_pune_2025_02, df_results_pune_2025_01])
df_results_jaipur_2025_06=pd.read_csv(data_dir / "datapack/results/jaipur/results_2025-06.csv.gz")
df_results_jaipur_2025_05=pd.read_csv(data_dir / "datapack/results/jaipur/results_2025-05.csv.gz")
df_results_jaipur_2025_04=pd.read_csv(data_dir / "datapack/results/jaipur/results_2025-04.csv.gz")
df_results_jaipur_2025_03=pd.read_csv(data_dir / "datapack/results/jaipur/results_2025-03.csv.gz")
df_results_jaipur_2025_02=pd.read_csv(data_dir / "datapack/results/jaipur/results_2025-02.csv.gz")
df_results_jaipur_2025_01=pd.read_csv(data_dir / "datapack/results/jaipur/results_2025-01.csv.gz")
display(df_results_jaipur_2025_06.shape,df_results_jaipur_2025_05.shape,df_results_jaipur_2025_04.shape,df_results_jaipur_2025_03.shape,df_results_jaipur_2025_02.shape,df_results_jaipur_2025_01.shape)
df_results_jaipur_2025_H1 = pd.concat([df_results_jaipur_2025_06, df_results_jaipur_2025_05, df_results_jaipur_2025_04, df_results_jaipur_2025_03, df_results_jaipur_2025_02, df_results_jaipur_2025_01])
df_results_jaipur_2025_H1.shape
df_results_hyderabad_2025_06=pd.read_csv(data_dir / "datapack/results/hyderabad/results_2025-06.csv.gz")
df_results_hyderabad_2025_05=pd.read_csv(data_dir / "datapack/results/hyderabad/results_2025-05.csv.gz")
df_results_hyderabad_2025_04=pd.read_csv(data_dir / "datapack/results/hyderabad/results_2025-04.csv.gz")
df_results_hyderabad_2025_03=pd.read_csv(data_dir / "datapack/results/hyderabad/results_2025-03.csv.gz")
df_results_hyderabad_2025_02=pd.read_csv(data_dir / "datapack/results/hyderabad/results_2025-02.csv.gz")
df_results_hyderabad_2025_01=pd.read_csv(data_dir / "datapack/results/hyderabad/results_2025-01.csv.gz")
display(df_results_hyderabad_2025_06.shape,df_results_hyderabad_2025_05.shape,df_results_hyderabad_2025_04.shape,df_results_hyderabad_2025_03.shape,df_results_hyderabad_2025_02.shape,df_results_hyderabad_2025_01.shape)
df_results_hyderabad_2025_H1 = pd.concat([df_results_hyderabad_2025_06, df_results_hyderabad_2025_05, df_results_hyderabad_2025_04, df_results_hyderabad_2025_03, df_results_hyderabad_2025_02, df_results_hyderabad_2025_01])
df_results_hyderabad_2025_H1.shape
df_results_chennai_2025_06=pd.read_csv(data_dir / "datapack/results/chennai/results_2025-06.csv.gz")
df_results_chennai_2025_05=pd.read_csv(data_dir / "datapack/results/chennai/results_2025-05.csv.gz")
df_results_chennai_2025_04=pd.read_csv(data_dir / "datapack/results/chennai/results_2025-04.csv.gz")
df_results_chennai_2025_03=pd.read_csv(data_dir / "datapack/results/chennai/results_2025-03.csv.gz")
df_results_chennai_2025_02=pd.read_csv(data_dir / "datapack/results/chennai/results_2025-02.csv.gz")
df_results_chennai_2025_01=pd.read_csv(data_dir / "datapack/results/chennai/results_2025-01.csv.gz")
display(df_results_chennai_2025_06.shape,df_results_chennai_2025_05.shape,df_results_chennai_2025_04.shape,df_results_chennai_2025_03.shape,df_results_chennai_2025_02.shape,df_results_chennai_2025_01.shape)
df_results_chennai_2025_H1 = pd.concat([df_results_chennai_2025_06, df_results_chennai_2025_05, df_results_chennai_2025_04, df_results_chennai_2025_03, df_results_chennai_2025_02, df_results_chennai_2025_01])
df_results_chennai_2025_H1.shape
df_results_bengaluru_2025_06=pd.read_csv(data_dir / "datapack/results/bengaluru/results_2025-06.csv.gz")
df_results_bengaluru_2025_05=pd.read_csv(data_dir / "datapack/results/bengaluru/results_2025-05.csv.gz")
df_results_bengaluru_2025_04=pd.read_csv(data_dir / "datapack/results/bengaluru/results_2025-04.csv.gz")
df_results_bengaluru_2025_03=pd.read_csv(data_dir / "datapack/results/bengaluru/results_2025-03.csv.gz")
df_results_bengaluru_2025_02=pd.read_csv(data_dir / "datapack/results/bengaluru/results_2025-02.csv.gz")
df_results_bengaluru_2025_01=pd.read_csv(data_dir / "datapack/results/bengaluru/results_2025-01.csv.gz")
display(df_results_bengaluru_2025_06.shape,df_results_bengaluru_2025_05.shape,df_results_bengaluru_2025_04.shape,df_results_bengaluru_2025_03.shape,df_results_bengaluru_2025_02.shape,df_results_bengaluru_2025_01.shape)
df_results_bengaluru_2025_H1 = pd.concat([df_results_bengaluru_2025_06, df_results_bengaluru_2025_05, df_results_bengaluru_2025_04, df_results_bengaluru_2025_03, df_results_bengaluru_2025_02, df_results_bengaluru_2025_01])
df_results_ahmedabad_2025_06=pd.read_csv(data_dir / "datapack/results/ahmedabad/results_2025-06.csv.gz")
df_results_ahmedabad_2025_05=pd.read_csv(data_dir / "datapack/results/ahmedabad/results_2025-05.csv.gz")
df_results_ahmedabad_2025_04=pd.read_csv(data_dir / "datapack/results/ahmedabad/results_2025-04.csv.gz")
df_results_ahmedabad_2025_03=pd.read_csv(data_dir / "datapack/results/ahmedabad/results_2025-03.csv.gz")
df_results_ahmedabad_2025_02=pd.read_csv(data_dir / "datapack/results/ahmedabad/results_2025-02.csv.gz")
df_results_ahmedabad_2025_01=pd.read_csv(data_dir / "datapack/results/ahmedabad/results_2025-01.csv.gz")
display(df_results_ahmedabad_2025_06.shape,df_results_ahmedabad_2025_05.shape,df_results_ahmedabad_2025_04.shape,df_results_ahmedabad_2025_03.shape,df_results_ahmedabad_2025_02.shape,df_results_ahmedabad_2025_01.shape)
df_results_ahmedabad_2025_H1 = pd.concat([df_results_ahmedabad_2025_06, df_results_ahmedabad_2025_05, df_results_ahmedabad_2025_04, df_results_ahmedabad_2025_03, df_results_ahmedabad_2025_02, df_results_ahmedabad_2025_01])

(8076, 5)

(8161, 5)

(8412, 5)

(8055, 5)

(8585, 5)

(8545, 5)

(5761, 5)

(6009, 5)

(5723, 5)

(6730, 5)

(6642, 5)

(6246, 5)

(9497, 5)

(9661, 5)

(10441, 5)

(10040, 5)

(10242, 5)

(10345, 5)

(10961, 5)

(10941, 5)

(10866, 5)

(11497, 5)

(10576, 5)

(10762, 5)

(13442, 5)

(13614, 5)

(13196, 5)

(14220, 5)

(13527, 5)

(13844, 5)

(10748, 5)

(10459, 5)

(10917, 5)

(10254, 5)

(10201, 5)

(10573, 5)

In [9]:
df_results_2025_H1 = pd.concat([df_results_pune_2025_H1,df_results_jaipur_2025_H1,df_results_hyderabad_2025_H1,df_results_chennai_2025_H1,df_results_bengaluru_2025_H1,df_results_ahmedabad_2025_H1])

In [10]:
df_results_2025_H1.shape

(357769, 5)

In [11]:
df_results_2025_H1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 357769 entries, 0 to 10572
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   booking_id    357769 non-null  object
 1   test_code     356716 non-null  object
 2   result_ts     357769 non-null  object
 3   result_value  357769 non-null  object
 4   result_flag   357769 non-null  object
dtypes: object(5)
memory usage: 16.4+ MB

In [12]:
import pandas as pd
df_bookings_pune_2026_06=pd.read_csv(data_dir / "datapack/bookings/legacy/pune/bookings_2026-06.csv.gz",encoding='latin-1')
df_bookings_pune_2026_05=pd.read_csv(data_dir / "datapack/bookings/legacy/pune/bookings_2026-05.csv.gz",encoding='latin-1')
df_bookings_pune_2026_04=pd.read_csv(data_dir / "datapack/bookings/legacy/pune/bookings_2026-04.csv.gz",encoding='latin-1')
df_bookings_pune_2026_03=pd.read_csv(data_dir / "datapack/bookings/legacy/pune/bookings_2026-03.csv.gz",encoding='latin-1')
df_bookings_pune_2026_02=pd.read_csv(data_dir / "datapack/bookings/legacy/pune/bookings_2026-02.csv.gz",encoding='latin-1')
df_bookings_pune_2026_01=pd.read_csv(data_dir / "datapack/bookings/legacy/pune/bookings_2026-01.csv.gz",encoding='latin-1')
display(df_bookings_pune_2026_06.shape,df_bookings_pune_2026_05.shape,df_bookings_pune_2026_04.shape,df_bookings_pune_2026_03.shape,df_bookings_pune_2026_02.shape,df_bookings_pune_2026_01.shape)
df_bookings_pune_2026_H1 = pd.concat([df_bookings_pune_2026_06, df_bookings_pune_2026_05, df_bookings_pune_2026_04, df_bookings_pune_2026_03, df_bookings_pune_2026_02, df_bookings_pune_2026_01])
df_bookings_pune_2026_H1.shape
df_bookings_jaipur_2026_06=pd.read_json(data_dir / "datapack/bookings/nova/jaipur/bookings_2026-06.jsonl.gz",lines=True)
df_bookings_jaipur_2026_05=pd.read_json(data_dir / "datapack/bookings/nova/jaipur/bookings_2026-05.jsonl.gz",lines=True)
df_bookings_jaipur_2026_04=pd.read_json(data_dir / "datapack/bookings/nova/jaipur/bookings_2026-04.jsonl.gz",lines=True)
df_bookings_jaipur_2026_03=pd.read_csv(data_dir / "datapack/bookings/legacy/jaipur/bookings_2026-03.csv.gz",encoding='latin-1')
df_bookings_jaipur_2026_02=pd.read_csv(data_dir / "datapack/bookings/legacy/jaipur/bookings_2026-02.csv.gz",encoding='latin-1')
df_bookings_jaipur_2026_01=pd.read_csv(data_dir / "datapack/bookings/legacy/jaipur/bookings_2026-01.csv.gz",encoding='latin-1')
display(df_bookings_jaipur_2026_06.shape,df_bookings_jaipur_2026_05.shape,df_bookings_jaipur_2026_04.shape,df_bookings_jaipur_2026_03.shape,df_bookings_jaipur_2026_02.shape,df_bookings_jaipur_2026_01.shape)
df_bookings_jaipur_2026_H1 = pd.concat([df_bookings_jaipur_2026_06, df_bookings_jaipur_2026_05, df_bookings_jaipur_2026_04, df_bookings_jaipur_2026_03, df_bookings_jaipur_2026_02, df_bookings_jaipur_2026_01])
df_bookings_jaipur_2026_H1.shape
df_bookings_hyderabad_2026_06=pd.read_csv(data_dir / "datapack/bookings/legacy/hyderabad/bookings_2026-06.csv.gz",encoding='latin-1')
df_bookings_hyderabad_2026_05=pd.read_csv(data_dir / "datapack/bookings/legacy/hyderabad/bookings_2026-05.csv.gz",encoding='latin-1')
df_bookings_hyderabad_2026_04=pd.read_csv(data_dir / "datapack/bookings/legacy/hyderabad/bookings_2026-04.csv.gz",encoding='latin-1')
df_bookings_hyderabad_2026_03=pd.read_csv(data_dir / "datapack/bookings/legacy/hyderabad/bookings_2026-03.csv.gz",encoding='latin-1')
df_bookings_hyderabad_2026_02=pd.read_csv(data_dir / "datapack/bookings/legacy/hyderabad/bookings_2026-02.csv.gz",encoding='latin-1')
df_bookings_hyderabad_2026_01=pd.read_csv(data_dir / "datapack/bookings/legacy/hyderabad/bookings_2026-01.csv.gz",encoding='latin-1')
display(df_bookings_hyderabad_2026_06.shape,df_bookings_hyderabad_2026_05.shape,df_bookings_hyderabad_2026_04.shape,df_bookings_hyderabad_2026_03.shape,df_bookings_hyderabad_2026_02.shape,df_bookings_hyderabad_2026_01.shape)
df_bookings_hyderabad_2026_H1 = pd.concat([df_bookings_hyderabad_2026_06, df_bookings_hyderabad_2026_05, df_bookings_hyderabad_2026_04, df_bookings_hyderabad_2026_03, df_bookings_hyderabad_2026_02, df_bookings_hyderabad_2026_01])
df_bookings_hyderabad_2026_H1.shape
df_bookings_chennai_2026_06=pd.read_json(data_dir / "datapack/bookings/nova/chennai/bookings_2026-06.jsonl.gz",lines=True)
df_bookings_chennai_2026_05=pd.read_json(data_dir / "datapack/bookings/nova/chennai/bookings_2026-05.jsonl.gz",lines=True)
df_bookings_chennai_2026_04=pd.read_json(data_dir / "datapack/bookings/nova/chennai/bookings_2026-04.jsonl.gz",lines=True)
df_bookings_chennai_2026_03=pd.read_csv(data_dir / "datapack/bookings/legacy/chennai/bookings_2026-03.csv.gz",encoding='latin-1')
df_bookings_chennai_2026_02=pd.read_csv(data_dir / "datapack/bookings/legacy/chennai/bookings_2026-02.csv.gz",encoding='latin-1')
df_bookings_chennai_2026_01=pd.read_csv(data_dir / "datapack/bookings/legacy/chennai/bookings_2026-01.csv.gz",encoding='latin-1')
display(df_bookings_chennai_2026_06.shape,df_bookings_chennai_2026_05.shape,df_bookings_chennai_2026_04.shape,df_bookings_chennai_2026_03.shape,df_bookings_chennai_2026_02.shape,df_bookings_chennai_2026_01.shape)
df_bookings_chennai_2026_H1 = pd.concat([df_bookings_chennai_2026_06, df_bookings_chennai_2026_05, df_bookings_chennai_2026_04, df_bookings_chennai_2026_03, df_bookings_chennai_2026_02, df_bookings_chennai_2026_01])
df_bookings_chennai_2026_H1.shape
df_bookings_bengaluru_2026_06=pd.read_csv(data_dir / "datapack/bookings/legacy/bengaluru/bookings_2026-06.csv.gz",encoding='latin-1')
df_bookings_bengaluru_2026_05=pd.read_csv(data_dir / "datapack/bookings/legacy/bengaluru/bookings_2026-05.csv.gz",encoding='latin-1')
df_bookings_bengaluru_2026_04=pd.read_csv(data_dir / "datapack/bookings/legacy/bengaluru/bookings_2026-04.csv.gz",encoding='latin-1')
df_bookings_bengaluru_2026_03=pd.read_csv(data_dir / "datapack/bookings/legacy/bengaluru/bookings_2026-03.csv.gz",encoding='latin-1')
df_bookings_bengaluru_2026_02=pd.read_csv(data_dir / "datapack/bookings/legacy/bengaluru/bookings_2026-02.csv.gz",encoding='latin-1')
df_bookings_bengaluru_2026_01=pd.read_csv(data_dir / "datapack/bookings/legacy/bengaluru/bookings_2026-01.csv.gz",encoding='latin-1')
display(df_bookings_bengaluru_2026_06.shape,df_bookings_bengaluru_2026_05.shape,df_bookings_bengaluru_2026_04.shape,df_bookings_bengaluru_2026_03.shape,df_bookings_bengaluru_2026_02.shape,df_bookings_bengaluru_2026_01.shape)
df_bookings_bengaluru_2026_H1 = pd.concat([df_bookings_bengaluru_2026_06, df_bookings_bengaluru_2026_05, df_bookings_bengaluru_2026_04, df_bookings_bengaluru_2026_03, df_bookings_bengaluru_2026_02, df_bookings_bengaluru_2026_01])
df_bookings_ahmedabad_2026_06=pd.read_csv(data_dir / "datapack/bookings/legacy/ahmedabad/bookings_2026-06.csv.gz",encoding='latin-1')
df_bookings_ahmedabad_2026_05=pd.read_csv(data_dir / "datapack/bookings/legacy/ahmedabad/bookings_2026-05.csv.gz",encoding='latin-1')
df_bookings_ahmedabad_2026_04=pd.read_csv(data_dir / "datapack/bookings/legacy/ahmedabad/bookings_2026-04.csv.gz",encoding='latin-1')
df_bookings_ahmedabad_2026_03=pd.read_csv(data_dir / "datapack/bookings/legacy/ahmedabad/bookings_2026-03.csv.gz",encoding='latin-1')
df_bookings_ahmedabad_2026_02=pd.read_csv(data_dir / "datapack/bookings/legacy/ahmedabad/bookings_2026-02.csv.gz",encoding='latin-1')
df_bookings_ahmedabad_2026_01=pd.read_csv(data_dir / "datapack/bookings/legacy/ahmedabad/bookings_2026-01.csv.gz",encoding='latin-1')
display(df_bookings_ahmedabad_2026_06.shape,df_bookings_ahmedabad_2026_05.shape,df_bookings_ahmedabad_2026_04.shape,df_bookings_ahmedabad_2026_03.shape,df_bookings_ahmedabad_2026_02.shape,df_bookings_ahmedabad_2026_01.shape)
df_bookings_ahmedabad_2026_H1 = pd.concat([df_bookings_ahmedabad_2026_06, df_bookings_ahmedabad_2026_05, df_bookings_ahmedabad_2026_04, df_bookings_ahmedabad_2026_03, df_bookings_ahmedabad_2026_02, df_bookings_ahmedabad_2026_01])

(10824, 12)

(9906, 12)

(10997, 12)

(11468, 12)

(10883, 12)

(11498, 12)

(3045, 12)

(2937, 12)

(2940, 12)

(6920, 12)

(6805, 12)

(6761, 12)

(13074, 12)

(12374, 12)

(13196, 12)

(13241, 12)

(13592, 12)

(13199, 12)

(5810, 12)

(5908, 12)

(5903, 12)

(13337, 12)

(14702, 12)

(13694, 12)

(16930, 12)

(17793, 12)

(17723, 12)

(17450, 12)

(19602, 12)

(18166, 12)

(14276, 12)

(13969, 12)

(13939, 12)

(14354, 12)

(14541, 12)

(14006, 12)

In [13]:
df_bookings_2026_H1= pd.concat([df_bookings_pune_2026_H1, df_bookings_jaipur_2026_H1, df_bookings_hyderabad_2026_H1, df_bookings_chennai_2026_H1, df_bookings_bengaluru_2026_H1, df_bookings_ahmedabad_2026_H1])

In [14]:
df_bookings_2026_H1.shape

(425763, 16)

In [15]:
df_bookings_2026_H1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 425763 entries, 0 to 14005
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   booking_id        425763 non-null  object
 1   created_at        425763 non-null  object
 2   slot_at           425763 non-null  object
 3   city              425763 non-null  object
 4   clinic_id         425763 non-null  object
 5   channel           425763 non-null  object
 6   source            425763 non-null  object
 7   patient_id        399220 non-null  object
 8   patient_name      399220 non-null  object
 9   test_code         398777 non-null  object
 10  test_price        399220 non-null  object
 11  home_fee          425763 non-null  object
 12  patient           26543 non-null   object
 13  tests             26543 non-null   object
 14  rescheduled_from  1500 non-null    object
 15  status_at_export  26543 non-null   object
dtypes: object(16)
memory usage: 55.2+ MB

In [16]:
import pandas as pd
df_bookings_pune_2025_06=pd.read_csv(data_dir / "datapack/bookings/legacy/pune/bookings_2025-06.csv.gz",encoding='latin-1')
df_bookings_pune_2025_05=pd.read_csv(data_dir / "datapack/bookings/legacy/pune/bookings_2025-05.csv.gz",encoding='latin-1')
df_bookings_pune_2025_04=pd.read_csv(data_dir / "datapack/bookings/legacy/pune/bookings_2025-04.csv.gz",encoding='latin-1')
df_bookings_pune_2025_03=pd.read_csv(data_dir / "datapack/bookings/legacy/pune/bookings_2025-03.csv.gz",encoding='latin-1')
df_bookings_pune_2025_02=pd.read_csv(data_dir / "datapack/bookings/legacy/pune/bookings_2025-02.csv.gz",encoding='latin-1')
df_bookings_pune_2025_01=pd.read_csv(data_dir / "datapack/bookings/legacy/pune/bookings_2025-01.csv.gz",encoding='latin-1')
display(df_bookings_pune_2025_06.shape,df_bookings_pune_2025_05.shape,df_bookings_pune_2025_04.shape,df_bookings_pune_2025_03.shape,df_bookings_pune_2025_02.shape,df_bookings_pune_2025_01.shape)
df_bookings_pune_2025_H1 = pd.concat([df_bookings_pune_2025_06, df_bookings_pune_2025_05, df_bookings_pune_2025_04, df_bookings_pune_2025_03, df_bookings_pune_2025_02, df_bookings_pune_2025_01])
df_bookings_pune_2025_H1.shape
df_bookings_jaipur_2025_06=pd.read_csv(data_dir / "datapack/bookings/legacy/jaipur/bookings_2025-06.csv.gz",encoding='latin-1')
df_bookings_jaipur_2025_05=pd.read_csv(data_dir / "datapack/bookings/legacy/jaipur/bookings_2025-05.csv.gz",encoding='latin-1')
df_bookings_jaipur_2025_04=pd.read_csv(data_dir / "datapack/bookings/legacy/jaipur/bookings_2025-04.csv.gz",encoding='latin-1')
df_bookings_jaipur_2025_03=pd.read_csv(data_dir / "datapack/bookings/legacy/jaipur/bookings_2025-03.csv.gz",encoding='latin-1')
df_bookings_jaipur_2025_02=pd.read_csv(data_dir / "datapack/bookings/legacy/jaipur/bookings_2025-02.csv.gz",encoding='latin-1')
df_bookings_jaipur_2025_01=pd.read_csv(data_dir / "datapack/bookings/legacy/jaipur/bookings_2025-01.csv.gz",encoding='latin-1')
display(df_bookings_jaipur_2025_06.shape,df_bookings_jaipur_2025_05.shape,df_bookings_jaipur_2025_04.shape,df_bookings_jaipur_2025_03.shape,df_bookings_jaipur_2025_02.shape,df_bookings_jaipur_2025_01.shape)
df_bookings_jaipur_2025_H1 = pd.concat([df_bookings_jaipur_2025_06, df_bookings_jaipur_2025_05, df_bookings_jaipur_2025_04, df_bookings_jaipur_2025_03, df_bookings_jaipur_2025_02, df_bookings_jaipur_2025_01])
df_bookings_jaipur_2025_H1.shape
df_bookings_hyderabad_2025_06=pd.read_csv(data_dir / "datapack/bookings/legacy/hyderabad/bookings_2025-06.csv.gz",encoding='latin-1')
df_bookings_hyderabad_2025_05=pd.read_csv(data_dir / "datapack/bookings/legacy/hyderabad/bookings_2025-05.csv.gz",encoding='latin-1')
df_bookings_hyderabad_2025_04=pd.read_csv(data_dir / "datapack/bookings/legacy/hyderabad/bookings_2025-04.csv.gz",encoding='latin-1')
df_bookings_hyderabad_2025_03=pd.read_csv(data_dir / "datapack/bookings/legacy/hyderabad/bookings_2025-03.csv.gz",encoding='latin-1')
df_bookings_hyderabad_2025_02=pd.read_csv(data_dir / "datapack/bookings/legacy/hyderabad/bookings_2025-02.csv.gz",encoding='latin-1')
df_bookings_hyderabad_2025_01=pd.read_csv(data_dir / "datapack/bookings/legacy/hyderabad/bookings_2025-01.csv.gz",encoding='latin-1')
display(df_bookings_hyderabad_2025_06.shape,df_bookings_hyderabad_2025_05.shape,df_bookings_hyderabad_2025_04.shape,df_bookings_hyderabad_2025_03.shape,df_bookings_hyderabad_2025_02.shape,df_bookings_hyderabad_2025_01.shape)
df_bookings_hyderabad_2025_H1 = pd.concat([df_bookings_hyderabad_2025_06, df_bookings_hyderabad_2025_05, df_bookings_hyderabad_2025_04, df_bookings_hyderabad_2025_03, df_bookings_hyderabad_2025_02, df_bookings_hyderabad_2025_01])
df_bookings_hyderabad_2025_H1.shape
df_bookings_chennai_2025_06=pd.read_csv(data_dir / "datapack/bookings/legacy/chennai/bookings_2025-06.csv.gz",encoding='latin-1')
df_bookings_chennai_2025_05=pd.read_csv(data_dir / "datapack/bookings/legacy/chennai/bookings_2025-05.csv.gz",encoding='latin-1')
df_bookings_chennai_2025_04=pd.read_csv(data_dir / "datapack/bookings/legacy/chennai/bookings_2025-04.csv.gz",encoding='latin-1')
df_bookings_chennai_2025_03=pd.read_csv(data_dir / "datapack/bookings/legacy/chennai/bookings_2025-03.csv.gz",encoding='latin-1')
df_bookings_chennai_2025_02=pd.read_csv(data_dir / "datapack/bookings/legacy/chennai/bookings_2025-02.csv.gz",encoding='latin-1')
df_bookings_chennai_2025_01=pd.read_csv(data_dir / "datapack/bookings/legacy/chennai/bookings_2025-01.csv.gz",encoding='latin-1')
display(df_bookings_chennai_2025_06.shape,df_bookings_chennai_2025_05.shape,df_bookings_chennai_2025_04.shape,df_bookings_chennai_2025_03.shape,df_bookings_chennai_2025_02.shape,df_bookings_chennai_2025_01.shape)
df_bookings_chennai_2025_H1 = pd.concat([df_bookings_chennai_2025_06, df_bookings_chennai_2025_05, df_bookings_chennai_2025_04, df_bookings_chennai_2025_03, df_bookings_chennai_2025_02, df_bookings_chennai_2025_01])
df_bookings_chennai_2025_H1.shape
df_bookings_bengaluru_2025_06=pd.read_csv(data_dir / "datapack/bookings/legacy/bengaluru/bookings_2025-06.csv.gz",encoding='latin-1')
df_bookings_bengaluru_2025_05=pd.read_csv(data_dir / "datapack/bookings/legacy/bengaluru/bookings_2025-05.csv.gz",encoding='latin-1')
df_bookings_bengaluru_2025_04=pd.read_csv(data_dir / "datapack/bookings/legacy/bengaluru/bookings_2025-04.csv.gz",encoding='latin-1')
df_bookings_bengaluru_2025_03=pd.read_csv(data_dir / "datapack/bookings/legacy/bengaluru/bookings_2025-03.csv.gz",encoding='latin-1')
df_bookings_bengaluru_2025_02=pd.read_csv(data_dir / "datapack/bookings/legacy/bengaluru/bookings_2025-02.csv.gz",encoding='latin-1')
df_bookings_bengaluru_2025_01=pd.read_csv(data_dir / "datapack/bookings/legacy/bengaluru/bookings_2025-01.csv.gz",encoding='latin-1')
display(df_bookings_bengaluru_2025_06.shape,df_bookings_bengaluru_2025_05.shape,df_bookings_bengaluru_2025_04.shape,df_bookings_bengaluru_2025_03.shape,df_bookings_bengaluru_2025_02.shape,df_bookings_bengaluru_2025_01.shape)
df_bookings_bengaluru_2025_H1 = pd.concat([df_bookings_bengaluru_2025_06, df_bookings_bengaluru_2025_05, df_bookings_bengaluru_2025_04, df_bookings_bengaluru_2025_03, df_bookings_bengaluru_2025_02, df_bookings_bengaluru_2025_01])
df_bookings_ahmedabad_2025_06=pd.read_csv(data_dir / "datapack/bookings/legacy/ahmedabad/bookings_2025-06.csv.gz",encoding='latin-1')
df_bookings_ahmedabad_2025_05=pd.read_csv(data_dir / "datapack/bookings/legacy/ahmedabad/bookings_2025-05.csv.gz",encoding='latin-1')
df_bookings_ahmedabad_2025_04=pd.read_csv(data_dir / "datapack/bookings/legacy/ahmedabad/bookings_2025-04.csv.gz",encoding='latin-1')
df_bookings_ahmedabad_2025_03=pd.read_csv(data_dir / "datapack/bookings/legacy/ahmedabad/bookings_2025-03.csv.gz",encoding='latin-1')
df_bookings_ahmedabad_2025_02=pd.read_csv(data_dir / "datapack/bookings/legacy/ahmedabad/bookings_2025-02.csv.gz",encoding='latin-1')
df_bookings_ahmedabad_2025_01=pd.read_csv(data_dir / "datapack/bookings/legacy/ahmedabad/bookings_2025-01.csv.gz",encoding='latin-1')
display(df_bookings_ahmedabad_2025_06.shape,df_bookings_ahmedabad_2025_05.shape,df_bookings_ahmedabad_2025_04.shape,df_bookings_ahmedabad_2025_03.shape,df_bookings_ahmedabad_2025_02.shape,df_bookings_ahmedabad_2025_01.shape)
df_bookings_ahmedabad_2025_H1 = pd.concat([df_bookings_ahmedabad_2025_06, df_bookings_ahmedabad_2025_05, df_bookings_ahmedabad_2025_04, df_bookings_ahmedabad_2025_03, df_bookings_ahmedabad_2025_02, df_bookings_ahmedabad_2025_01])

(9931, 12)

(9898, 12)

(10192, 12)

(9855, 12)

(10412, 12)

(10366, 12)

(6929, 12)

(7314, 12)

(6909, 12)

(8288, 12)

(8078, 12)

(7632, 12)

(11605, 12)

(11866, 12)

(12632, 12)

(12028, 12)

(12534, 12)

(12576, 12)

(13373, 12)

(13258, 12)

(13411, 12)

(14133, 12)

(12867, 12)

(13226, 12)

(16379, 12)

(16569, 12)

(16059, 12)

(17516, 12)

(16564, 12)

(16983, 12)

(13067, 12)

(12728, 12)

(13227, 12)

(12537, 12)

(12554, 12)

(12813, 12)

In [17]:
df_bookings_2025_H1 = pd.concat([df_bookings_ahmedabad_2025_H1, df_bookings_bengaluru_2025_H1, df_bookings_chennai_2025_H1, df_bookings_hyderabad_2025_H1, df_bookings_jaipur_2025_H1, df_bookings_pune_2025_H1])

In [18]:
df_bookings_2025_H1.shape

(436309, 12)

In [19]:
df_bookings_2025_H1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 436309 entries, 0 to 10365
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   booking_id    436309 non-null  object
 1   created_at    436309 non-null  object
 2   slot_at       436309 non-null  object
 3   city          436309 non-null  object
 4   clinic_id     436309 non-null  object
 5   channel       436309 non-null  object
 6   source        436309 non-null  object
 7   patient_id    436309 non-null  object
 8   patient_name  436309 non-null  object
 9   test_code     435887 non-null  object
 10  test_price    436309 non-null  object
 11  home_fee      436309 non-null  object
dtypes: object(12)
memory usage: 43.3+ MB

In [20]:
import pandas as pd

def recover_missing_test_codes(bookings_df, results_df):
    """
    Recover missing test_code values when exactly one booked code
    is absent from the recorded results for that booking.

    Returns:
        cleaned_results: copy of results with inferred codes filled
        audit: DataFrame showing each missing row and its status
    """
    cleaned_results = results_df.copy()

    # Identify rows with missing test codes
    missing_mask = cleaned_results["test_code"].isna()

    if not missing_mask.any():
        return cleaned_results, pd.DataFrame()

    missing_ids = cleaned_results.loc[
        missing_mask, "booking_id"
    ].unique()

    # Unique booked codes for affected bookings
    booked_codes = (
        bookings_df[
            bookings_df["booking_id"].isin(missing_ids)
        ]
        .dropna(subset=["test_code"])
        .groupby("booking_id")["test_code"]
        .agg(lambda s: set(s))
    )

    # Existing recorded result codes for affected bookings
    recorded_codes = (
        cleaned_results[
            cleaned_results["booking_id"].isin(missing_ids)
        ]
        .dropna(subset=["test_code"])
        .groupby("booking_id")["test_code"]
        .agg(lambda s: set(s))
    )

    audit_rows = []

    for idx in cleaned_results.index[missing_mask]:
        booking_id = cleaned_results.at[idx, "booking_id"]

        booked = booked_codes.get(booking_id, set())
        recorded = recorded_codes.get(booking_id, set())

        candidates = booked - recorded

        if len(candidates) == 1:
            inferred_code = next(iter(candidates))
            cleaned_results.at[idx, "test_code"] = inferred_code
            status = "inferred_unique_candidate"
        else:
            inferred_code = None
            status = (
                "ambiguous"
                if len(candidates) > 1
                else "no_candidate"
            )

        audit_rows.append({
            "row_index": idx,
            "booking_id": booking_id,
            "inferred_test_code": inferred_code,
            "candidate_codes": sorted(candidates),
            "status": status
        })

    audit = pd.DataFrame(audit_rows)

    return cleaned_results, audit

In [21]:
df_results_2026_H1_clean, audit_2026 = recover_missing_test_codes(
    df_bookings_2026_H1,
    df_results_2026_H1
)

df_results_2025_H1_clean, audit_2025 = recover_missing_test_codes(
    df_bookings_2025_H1,
    df_results_2025_H1
)
print("2026 H1")
print(audit_2026["status"].value_counts())
print("Missing codes remaining:",
      df_results_2026_H1_clean["test_code"].isna().sum())

print("\n2025 H1")
print(audit_2025["status"].value_counts())
print("Missing codes remaining:",
      df_results_2025_H1_clean["test_code"].isna().sum())

2026 H1
status
no_candidate                 1140
inferred_unique_candidate       9
Name: count, dtype: int64
Missing codes remaining: 1140

2025 H1
status
no_candidate                 1052
inferred_unique_candidate       1
Name: count, dtype: int64
Missing codes remaining: 1052

In [22]:

def diagnose_test_codes(bookings, results, year):
    print(f"\n===== {year} H1 =====")

    print("Booking rows:", len(bookings))
    print("Result rows:", len(results))

    print("\nMissing test_code values:")
    print("Bookings:", bookings["test_code"].isna().sum())
    print("Results:", results["test_code"].isna().sum())

    print("\nMissing booking_id values:")
    print("Bookings:", bookings["booking_id"].isna().sum())
    print("Results:", results["booking_id"].isna().sum())

    print("\nUnique booking IDs:")
    print("Bookings:", bookings["booking_id"].nunique())
    print("Results:", results["booking_id"].nunique())

    booking_ids = set(bookings["booking_id"].dropna())
    result_ids = set(results["booking_id"].dropna())

    print("\nBooking IDs in results but not bookings:",
          len(result_ids - booking_ids))
    print("Booking IDs in bookings but not results:",
          len(booking_ids - result_ids))

    missing = results[results["test_code"].isna()]
    print("\nMissing-code rows by booking-ID match:")
    print("With matching booking ID:",
          missing["booking_id"].isin(booking_ids).sum())
    print("Without matching booking ID:",
          (~missing["booking_id"].isin(booking_ids)).sum())


diagnose_test_codes(
    df_bookings_2026_H1, df_results_2026_H1, 2026
)

diagnose_test_codes(
    df_bookings_2025_H1, df_results_2025_H1, 2025
)

===== 2026 H1 =====
Booking rows: 425763
Result rows: 378358

Missing test_code values:
Bookings: 26986
Results: 1149

Missing booking_id values:
Bookings: 0
Results: 0

Unique booking IDs:
Bookings: 196589
Results: 164053

Booking IDs in results but not bookings: 3305
Booking IDs in bookings but not results: 35841

Missing-code rows by booking-ID match:
With matching booking ID: 1136
Without matching booking ID: 13

===== 2025 H1 =====
Booking rows: 436309
Result rows: 357769

Missing test_code values:
Bookings: 422
Results: 1053

Missing booking_id values:
Bookings: 0
Results: 0

Unique booking IDs:
Bookings: 189878
Results: 158453

Booking IDs in results but not bookings: 3268
Booking IDs in bookings but not results: 34693

Missing-code rows by booking-ID match:
With matching booking ID: 1041
Without matching booking ID: 12

In [23]:

import pandas as pd

def recover_missing_test_codes(bookings, results):
    results = results.copy()

    # Preserve original values for auditing
    results["test_code_original"] = results["test_code"]

    # Normalize codes and IDs for comparison
    b = bookings[["booking_id", "test_code"]].copy()
    b["test_code"] = b["test_code"].replace(r"^\s*$", pd.NA, regex=True)

    r = results[["booking_id", "test_code"]].copy()
    r["test_code"] = r["test_code"].replace(r"^\s*$", pd.NA, regex=True)

    # Distinct codes booked per booking ID
    booked = (
        b.dropna(subset=["test_code"])
         .groupby("booking_id")["test_code"]
         .agg(lambda x: set(x))
    )

    # Distinct codes already recorded per booking ID
    recorded = (
        r.dropna(subset=["test_code"])
         .groupby("booking_id")["test_code"]
         .agg(lambda x: set(x))
    )

    missing_mask = results["test_code"].isna()
    inferred_codes = []
    statuses = []

    for _, row in results.loc[missing_mask].iterrows():
        bid = row["booking_id"]

        booked_codes = booked.get(bid, set())
        recorded_codes = recorded.get(bid, set())

        # Codes booked but not already represented in results
        candidates = booked_codes - recorded_codes

        if len(candidates) == 1:
            inferred_codes.append(next(iter(candidates)))
            statuses.append("inferred_unique_candidate")
        elif len(candidates) > 1:
            inferred_codes.append(pd.NA)
            statuses.append("ambiguous_multiple_candidates")
        elif bid not in booked.index:
            inferred_codes.append(pd.NA)
            statuses.append("booking_not_found_or_no_codes")
        else:
            inferred_codes.append(pd.NA)
            statuses.append("no_unrecorded_candidate")

    # Update only uniquely inferred missing values
    results.loc[missing_mask, "test_code"] = inferred_codes
    results["recovery_status"] = "original_code_present"
    results.loc[missing_mask, "recovery_status"] = statuses

    audit = results.loc[missing_mask].copy()

    return results, audit

df_results_2026_H1_clean, audit_2026 = recover_missing_test_codes(
    df_bookings_2026_H1,
    df_results_2026_H1
)

df_results_2025_H1_clean, audit_2025 = recover_missing_test_codes(
    df_bookings_2025_H1,
    df_results_2025_H1
)

print("2026 H1")
print(audit_2026["recovery_status"].value_counts())
print("Missing codes remaining:",
      df_results_2026_H1_clean["test_code"].isna().sum())

print("\n2025 H1")
print(audit_2025["recovery_status"].value_counts())
print("Missing codes remaining:",
      df_results_2025_H1_clean["test_code"].isna().sum())

2026 H1
recovery_status
inferred_unique_candidate        939
booking_not_found_or_no_codes    159
ambiguous_multiple_candidates     47
no_unrecorded_candidate            4
Name: count, dtype: int64
Missing codes remaining: 210

2025 H1
recovery_status
inferred_unique_candidate        1011
ambiguous_multiple_candidates      29
booking_not_found_or_no_codes      12
no_unrecorded_candidate             1
Name: count, dtype: int64
Missing codes remaining: 42

In [24]:

unresolved_2026 = df_results_2026_H1_clean[
    df_results_2026_H1_clean["test_code"].isna()
].copy()

unresolved_2025 = df_results_2025_H1_clean[
    df_results_2025_H1_clean["test_code"].isna()
].copy()

print("2026 unresolved rows:", len(unresolved_2026))
display(unresolved_2026.head(20))

print("2025 unresolved rows:", len(unresolved_2025))
display(unresolved_2025.head(20))

2026 unresolved rows: 210

,booking_id,test_code,result_ts,result_value,result_flag,test_code_original,recovery_status
5361,BK-PUN-202606-078189,<NA>,2026-06-09 16:22:00,80.2,flag,NaN,ambiguous_multiple_candidates
2741,BK-PUN-202605-072492,<NA>,2026-05-19 14:57:00,92.8,normal,NaN,ambiguous_multiple_candidates
3879,BK-PUN-202605-073061,<NA>,2026-05-07 02:17:00,45.4,normal,NaN,ambiguous_multiple_candidates
7049,BK-PUN-202605-074762,<NA>,2026-05-27 10:21:00,60.1,flag,NaN,ambiguous_multiple_candidates
4049,BK-PUN-202604-068480,<NA>,2026-04-23 21:49:00,17.7,normal,NaN,ambiguous_multiple_candidates
4050,BK-PUN-202604-068480,<NA>,2026-04-23 21:49:00,6.7,normal,NaN,ambiguous_multiple_candidates
5811,BK-PUN-202603-064431,<NA>,2026-03-26 14:41:00,52.2,flag,NaN,ambiguous_multiple_candidates
1825,BK-PUN-202602-962053,<NA>,2026-02-14 19:56:00,50.3,normal,NaN,booking_not_found_or_no_codes
7171,BK-PUN-202601-055597,<NA>,2026-01-12 05:39:00,51.4,flag,NaN,ambiguous_multiple_candidates
204,nova_jai_0052820,<NA>,2026-06-14 18:04:00,58.7,normal,NaN,booking_not_found_or_no_codes
208,nova_jai_0052823,<NA>,2026-06-04 09:14:00,49.0,normal,NaN,booking_not_found_or_no_codes
233,nova_jai_0052831,<NA>,2026-06-30 09:54:00,71.4,normal,NaN,booking_not_found_or_no_codes
247,nova_jai_0052840,<NA>,2026-06-03 21:04:00,39.2,normal,NaN,booking_not_found_or_no_codes
796,nova_jai_0053125,<NA>,2026-06-19 18:05:00,27.5,normal,NaN,booking_not_found_or_no_codes
830,nova_jai_0053138,<NA>,2026-06-05 21:07:00,28.3,normal,NaN,booking_not_found_or_no_codes
1124,nova_jai_0053290,<NA>,2026-06-21 16:30:00,64.4,flag,NaN,booking_not_found_or_no_codes
1480,nova_jai_0053486,<NA>,2026-06-07 05:13:00,69.2,normal,NaN,booking_not_found_or_no_codes
1542,nova_jai_0053519,<NA>,2026-06-02 01:44:00,47.9,normal,NaN,booking_not_found_or_no_codes
1847,nova_jai_0053673,<NA>,2026-06-11 13:56:00,45.0,normal,NaN,booking_not_found_or_no_codes
1909,nova_jai_0053704,<NA>,2026-06-10 13:40:00,73.1,normal,NaN,booking_not_found_or_no_codes

2025 unresolved rows: 42

,booking_id,test_code,result_ts,result_value,result_flag,test_code_original,recovery_status
6924,BK-PUN-202505-021421,<NA>,2025-06-01 16:21:00,49.5,normal,NaN,ambiguous_multiple_candidates
1448,BK-PUN-202502-005279,<NA>,2025-02-27 17:30:00,51.8,normal,NaN,ambiguous_multiple_candidates
5786,BK-PUN-202502-007565,<NA>,2025-02-24 02:46:00,51.5,normal,NaN,ambiguous_multiple_candidates
5933,BK-PUN-202502-007638,<NA>,2025-02-07 09:52:00,83.4,normal,NaN,ambiguous_multiple_candidates
6638,BK-PUN-202501-003529,<NA>,2025-01-19 18:31:00,56.7,normal,NaN,ambiguous_multiple_candidates
3158,BK-JAI-202505-980019,<NA>,2025-05-04 12:24:00,48.1,normal,NaN,booking_not_found_or_no_codes
5367,BK-JAI-202505-016257,<NA>,2025-05-09 17:07:00,51.4,flag,NaN,ambiguous_multiple_candidates
6022,BK-HYD-202506-029935,<NA>,2025-06-25 00:03:00,50.6,flag,NaN,ambiguous_multiple_candidates
5761,BK-HYD-202505-024624,<NA>,2025-04-30 00:55:00,12.1,flag,NaN,ambiguous_multiple_candidates
8386,BK-HYD-202505-026045,<NA>,2025-05-26 11:25:00,67.7,normal,NaN,ambiguous_multiple_candidates
8658,BK-HYD-202505-962474,<NA>,2025-05-22 23:22:00,63.4,normal,NaN,booking_not_found_or_no_codes
3516,BK-HYD-202504-017952,<NA>,2025-04-27 21:29:00,29.8,normal,NaN,ambiguous_multiple_candidates
6866,BK-HYD-202504-957335,<NA>,2025-04-28 21:25:00,51.0,flag,NaN,booking_not_found_or_no_codes
5902,BK-HYD-202503-013934,<NA>,2025-03-21 19:10:00,77.9,flag,NaN,booking_not_found_or_no_codes
1597,BK-HYD-202501-000843,<NA>,2025-01-31 13:13:00,75.0,normal,NaN,ambiguous_multiple_candidates
1702,BK-HYD-202501-991735,<NA>,2025-01-23 02:43:00,51.7,flag,NaN,booking_not_found_or_no_codes
5696,BK-CHE-202506-032183,<NA>,2025-06-03 07:38:00,85.2,normal,NaN,ambiguous_multiple_candidates
1207,BK-CHE-202504-018117,<NA>,2025-04-12 11:44:00,74.9,normal,NaN,no_unrecorded_candidate
5533,BK-CHE-202504-020432,<NA>,2025-04-30 14:40:00,54.2,flag,NaN,ambiguous_multiple_candidates
3297,BK-CHE-202503-013063,<NA>,2025-03-29 18:23:00,38.4,flag,NaN,ambiguous_multiple_candidates

In [25]:

def inspect_ambiguous(audit, bookings):
    ids = audit.loc[
        audit["recovery_status"] == "ambiguous_multiple_candidates",
        "booking_id"
    ].unique()

    return (
        bookings[bookings["booking_id"].isin(ids)]
        [["booking_id", "test_code"]]
        .drop_duplicates()
        .sort_values(["booking_id", "test_code"])
    )

ambiguous_2026 = inspect_ambiguous(audit_2026, df_bookings_2026_H1)
ambiguous_2025 = inspect_ambiguous(audit_2025, df_bookings_2025_H1)

display(ambiguous_2026)
display(ambiguous_2025)

                booking_id test_code
449   BK-AHM-202601-065485      T001
447   BK-AHM-202601-065485      T007
448   BK-AHM-202601-065485      T009
5074  BK-AHM-202601-067463      PK04
5073  BK-AHM-202601-067463      T010
...                    ...       ...
6572  BK-PUN-202606-078189      T001
6569  BK-PUN-202606-078189      T004
6574  BK-PUN-202606-078189      T005
6571  BK-PUN-202606-078189      T006
6573  BK-PUN-202606-078189      T010

[152 rows x 2 columns]

                booking_id test_code
8553  BK-AHM-202504-020236      T002
8554  BK-AHM-202504-020236      T003
8552  BK-AHM-202504-020236      T010
6977  BK-AHM-202505-025330      PK03
6978  BK-AHM-202505-025330      T002
...                    ...       ...
7208  BK-PUN-202502-007638      T016
8424  BK-PUN-202505-021421      PK02
8425  BK-PUN-202505-021421      T002
8423  BK-PUN-202505-021421      T003
8422  BK-PUN-202505-021421      T019

[100 rows x 2 columns]

In [26]:
df_bookings_chennai_2026_04.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5903 entries, 0 to 5902
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   booking_id        5903 non-null   object
 1   created_at        5903 non-null   datetime64[ns, UTC+05:30]
 2   slot_at           5903 non-null   datetime64[ns, UTC+05:30]
 3   city              5903 non-null   object
 4   clinic_id         5903 non-null   object
 5   channel           5903 non-null   object
 6   source            5903 non-null   object
 7   patient           5903 non-null   object
 8   tests             5903 non-null   object
 9   home_fee          5903 non-null   int64
 10  rescheduled_from  334 non-null    object
 11  status_at_export  5903 non-null   object
dtypes: datetime64[ns, UTC+05:30](2), int64(1), object(9)
memory usage: 553.5+ KB

In [27]:
df_bookings_chennai_2026_04.head()

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient,tests,home_fee,rescheduled_from,status_at_export
0,nova_che_0087556,2026-04-21 01:57:00+05:30,2026-04-25 10:16:00+05:30,Chennai,CHE-01,CLINIC,WALKIN,"{'patient_id': 'PCHE0044922', 'is_new': False}","[{'code': 'T007', 'price': 550}]",0,None,booked
1,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,"{'patient_id': 'PCHE0047035', 'is_new': False}","[{'code': 'T007', 'price': 550}, {'code': 'T01...",0,None,booked
2,nova_che_0087558,2026-04-28 04:46:00+05:30,2026-04-30 08:19:00+05:30,Chennai,CHE-05,CLINIC,PHONE,"{'patient_id': 'PCHE0051652', 'is_new': False}","[{'code': 'T004', 'price': 650}, {'code': 'T00...",0,None,booked
3,nova_che_0087559,2026-04-16 05:53:00+05:30,2026-04-21 08:08:00+05:30,Chennai,CHE-02,HOME,APP,"{'patient_id': 'PCHE0040733', 'is_new': False}","[{'code': 'T006', 'price': 650}, {'code': 'T00...",150,None,booked
4,nova_che_0087560,2026-04-07 05:57:00+05:30,2026-04-08 08:46:00+05:30,Chennai,CHE-05,CLINIC,WALKIN,"{'patient_id': 'PCHE0037380', 'is_new': False}","[{'code': 'T007', 'price': 550}]",0,None,rescheduled

In [28]:
df_results_chennai_2026_04.head()

         booking_id test_code            result_ts result_value result_flag
0  nova_che_0087556      T007  2026-04-26 13:10:00         52.5        flag
1  nova_che_0087558      T004  2026-04-30 15:17:00         21.0      normal
2  nova_che_0087558      T001  2026-05-01 01:17:00         56.1      normal
3  nova_che_0087559      T006  2026-04-21 17:55:00         13.4        flag
4  nova_che_0087559      T007  2026-04-22 08:55:00         24.5      normal

In [29]:

import pandas as pd
import ast

def normalize_new_bookings(df):
    df = df.copy()

    def parse_tests(value):
        if isinstance(value, list):
            return value
        if isinstance(value, str):
            try:
                parsed = ast.literal_eval(value)
                return parsed if isinstance(parsed, list) else []
            except (ValueError, SyntaxError):
                return []
        return []

    df["tests"] = df["tests"].apply(parse_tests)

    df = df.explode("tests", ignore_index=True)

    df["test_code"] = df["tests"].apply(
        lambda x: x.get("code") if isinstance(x, dict) else pd.NA
    )

    df["test_price"] = df["tests"].apply(
        lambda x: x.get("price") if isinstance(x, dict) else pd.NA
    )

    return df.drop(columns=["tests"])
    df_bookings_jaipur_chennai_clean = normalize_new_bookings(
    df_bookings_new
)

display(df_bookings_jaipur_chennai_clean.head(10))

print("Shape:", df_bookings_jaipur_chennai_clean.shape)
print("Missing test codes:",
      df_bookings_jaipur_chennai_clean["test_code"].isna().sum())

NameError: name 'df_bookings_jaipur_chennai_clean' is not defined

In [30]:

import pandas as pd
import ast

def normalize_new_bookings(df):
    df = df.copy()

    def parse_tests(value):
        if isinstance(value, list):
            return value
        if isinstance(value, str):
            try:
                result = ast.literal_eval(value)
                return result if isinstance(result, list) else []
            except (ValueError, SyntaxError):
                return []
        return []

    df["tests"] = df["tests"].apply(parse_tests)
    df = df.explode("tests", ignore_index=True)

    df["test_code"] = df["tests"].apply(
        lambda x: x.get("code") if isinstance(x, dict) else pd.NA
    )
    df["test_price"] = df["tests"].apply(
        lambda x: x.get("price") if isinstance(x, dict) else pd.NA
    )

    return df.drop(columns=["tests"])


# Combine April, May and June 2026
new_booking_dfs = [
    df_bookings_chennai_2026_04,
    df_bookings_chennai_2026_05,
    df_bookings_chennai_2026_06,
    df_bookings_jaipur_2026_04,
    df_bookings_jaipur_2026_05,
    df_bookings_jaipur_2026_06,
]

df_bookings_chennai_jaipur_2026 = pd.concat(
    new_booking_dfs, ignore_index=True
)

df_bookings_chennai_jaipur_2026_clean = normalize_new_bookings(
    df_bookings_chennai_jaipur_2026
)

print("Shape:", df_bookings_chennai_jaipur_2026_clean.shape)
print("Missing test codes:",
      df_bookings_chennai_jaipur_2026_clean["test_code"].isna().sum())

display(df_bookings_chennai_jaipur_2026_clean.head())

display(
    df_bookings_chennai_jaipur_2026_clean[
        df_bookings_chennai_jaipur_2026_clean["booking_id"]
        == "nova_che_0087556"
    ][["booking_id", "city", "test_code", "test_price"]]
)

Shape: (62439, 13)
Missing test codes: 21

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient,home_fee,rescheduled_from,status_at_export,test_code,test_price
0,nova_che_0087556,2026-04-21 01:57:00+05:30,2026-04-25 10:16:00+05:30,Chennai,CHE-01,CLINIC,WALKIN,"{'patient_id': 'PCHE0044922', 'is_new': False}",0,None,booked,T007,550
1,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,"{'patient_id': 'PCHE0047035', 'is_new': False}",0,None,booked,T007,550
2,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,"{'patient_id': 'PCHE0047035', 'is_new': False}",0,None,booked,T011,750
3,nova_che_0087557,2026-03-28 03:02:00+05:30,2026-04-01 09:17:00+05:30,Chennai,CHE-03,CLINIC,PHONE,"{'patient_id': 'PCHE0047035', 'is_new': False}",0,None,booked,T004,650
4,nova_che_0087558,2026-04-28 04:46:00+05:30,2026-04-30 08:19:00+05:30,Chennai,CHE-05,CLINIC,PHONE,"{'patient_id': 'PCHE0051652', 'is_new': False}",0,None,booked,T004,650

         booking_id     city test_code test_price
0  nova_che_0087556  Chennai      T007        550

In [31]:
missing_booking_codes = df_bookings_chennai_jaipur_2026_clean[
    df_bookings_chennai_jaipur_2026_clean["test_code"].isna()
]

display(
    missing_booking_codes[
        ["booking_id", "city", "created_at", "slot_at", "status_at_export"]
    ]
)

print("Missing-code rows by city:")
print(missing_booking_codes["city"].value_counts(dropna=False))

,booking_id,city,created_at,slot_at,status_at_export
4066,nova_che_0089328,Chennai,2026-04-21 01:07:00+05:30,2026-04-25 07:51:00+05:30,rescheduled
4401,nova_che_0089478,Chennai,2026-04-04 03:51:00+05:30,2026-04-08 06:06:00+05:30,booked
7321,nova_che_0090675,Chennai,2026-04-12 03:05:00+05:30,2026-04-14 08:17:00+05:30,booked
8575,nova_che_0091224,Chennai,2026-04-02 03:49:00+05:30,2026-04-07 06:32:00+05:30,booked
12000,nova_che_0092700,Chennai,2026-03-28 04:58:00+05:30,2026-04-02 11:12:00+05:30,booked
15467,nova_che_0094144,Chennai,2026-05-19 03:11:00+05:30,2026-05-22 09:10:00+05:30,booked
16425,nova_che_0094567,Chennai,2026-05-23 02:31:00+05:30,2026-05-27 07:54:00+05:30,booked
18240,nova_che_0095338,Chennai,2026-05-13 21:29:00+05:30,2026-05-18 07:14:00+05:30,booked
20437,nova_che_0096263,Chennai,2026-05-04 02:04:00+05:30,2026-05-07 07:59:00+05:30,booked
21110,nova_che_0096550,Chennai,2026-05-12 04:35:00+05:30,2026-05-16 09:38:00+05:30,booked
28647,nova_che_0099742,Chennai,2026-06-09 08:54:00+05:30,2026-06-14 17:31:00+05:30,booked
29196,nova_che_0099971,Chennai,2026-06-07 02:03:00+05:30,2026-06-07 06:54:00+05:30,booked
33631,nova_che_0101855,Chennai,2026-06-02 06:13:00+05:30,2026-06-07 06:31:00+05:30,booked
37464,nova_che_0103496,Chennai,2026-05-29 13:52:00+05:30,2026-06-01 16:43:00+05:30,booked
40559,nova_che_0104810,Chennai,2026-06-10 10:20:00+05:30,2026-06-15 17:59:00+05:30,booked
42909,nova_jai_0047467,Jaipur,2026-04-18 06:51:00+05:30,2026-04-22 08:48:00+05:30,booked
44200,nova_jai_0048026,Jaipur,2026-04-21 05:50:00+05:30,2026-04-23 12:53:00+05:30,booked
48650,nova_jai_0049911,Jaipur,2026-05-11 06:48:00+05:30,2026-05-11 13:53:00+05:30,booked
54421,nova_jai_0052368,Jaipur,2026-05-06 23:12:00+05:30,2026-05-11 07:20:00+05:30,booked
57189,nova_jai_0053556,Jaipur,2026-06-28 05:08:00+05:30,2026-06-28 07:33:00+05:30,booked
58388,nova_jai_0054051,Jaipur,2026-06-12 05:15:00+05:30,2026-06-16 09:06:00+05:30,booked

Missing-code rows by city:
city
Chennai    15
Jaipur      6
Name: count, dtype: int64

In [32]:

missing_ids = set(
    missing_booking_codes["booking_id"].dropna()
)

monthly_bookings = [
    df_bookings_chennai_2026_04,
    df_bookings_chennai_2026_05,
    df_bookings_chennai_2026_06,
    df_bookings_jaipur_2026_04,
    df_bookings_jaipur_2026_05,
    df_bookings_jaipur_2026_06,
]

original_missing = pd.concat(
    [
        df[df["booking_id"].isin(missing_ids)]
        for df in monthly_bookings
    ],
    ignore_index=True
)

display(
    original_missing[
        [
            "booking_id",
            "city",
            "tests",
            "status_at_export",
            "rescheduled_from",
        ]
    ]
)

          booking_id     city tests status_at_export rescheduled_from
0   nova_che_0089328  Chennai    []      rescheduled             None
1   nova_che_0089478  Chennai    []           booked             None
2   nova_che_0090675  Chennai    []           booked             None
3   nova_che_0091224  Chennai    []           booked             None
4   nova_che_0092700  Chennai    []           booked             None
5   nova_che_0094144  Chennai    []           booked             None
6   nova_che_0094567  Chennai    []           booked             None
7   nova_che_0095338  Chennai    []           booked             None
8   nova_che_0096263  Chennai    []           booked             None
9   nova_che_0096550  Chennai    []           booked             None
10  nova_che_0099742  Chennai    []           booked             None
11  nova_che_0099971  Chennai    []           booked             None
12  nova_che_0101855  Chennai    []           booked             None
13  nova_che_0103496  Chennai    []           booked             None
14  nova_che_0104810  Chennai    []           booked             None
15  nova_jai_0047467   Jaipur    []           booked             None
16  nova_jai_0048026   Jaipur    []           booked             None
17  nova_jai_0049911   Jaipur    []           booked             None
18  nova_jai_0052368   Jaipur    []           booked             None
19  nova_jai_0053556   Jaipur    []           booked             None
20  nova_jai_0054051   Jaipur    []           booked             None

In [33]:
print("Results duplicate columns:",
      df_results_2026_H1.columns[
          df_results_2026_H1.columns.duplicated()
      ].tolist())

print("Bookings duplicate columns:",
      df_bookings_2026_H1.columns[
          df_bookings_2026_H1.columns.duplicated()
      ].tolist())

print("Results booking_id column count:",
      list(df_results_2026_H1.columns).count("booking_id"))

print("Bookings booking_id column count:",
      list(df_bookings_2026_H1.columns).count("booking_id"))

Results duplicate columns: []
Bookings duplicate columns: []
Results booking_id column count: 1
Bookings booking_id column count: 1

In [34]:
# Check booking_id types in both DataFrames
print("Results booking_id dtype:",
      df_results_2026_H1["booking_id"].dtype)

print("Bookings booking_id dtype:",
      df_bookings_2026_H1["booking_id"].dtype)

print("\nResults booking_id sample:")
print(df_results_2026_H1["booking_id"].head())

print("\nBookings booking_id sample:")
print(df_bookings_2026_H1["booking_id"].head())

# Check whether any booking_id values are Series
print("\nResults contains Series values:",
      df_results_2026_H1["booking_id"].apply(
          lambda x: isinstance(x, pd.Series)
      ).any())

print("Bookings contains Series values:",
      df_bookings_2026_H1["booking_id"].apply(
          lambda x: isinstance(x, pd.Series)
      ).any())

Results booking_id dtype: object
Bookings booking_id dtype: object

Results booking_id sample:
0    BK-PUN-202606-075346
1    BK-PUN-202606-075347
2    BK-PUN-202606-075347
3    BK-PUN-202606-075348
4    BK-PUN-202606-075348
Name: booking_id, dtype: object

Bookings booking_id sample:
0    BK-PUN-202606-075346
1    BK-PUN-202606-075347
2    BK-PUN-202606-075347
3    BK-PUN-202606-075348
4    BK-PUN-202606-075348
Name: booking_id, dtype: object

Results contains Series values: False
Bookings contains Series values: False

In [35]:
print("\nBooking columns:")
print(df_bookings_2026_H1.columns.tolist())

print("\nSample tests values:")
if "tests" in df_bookings_2026_H1.columns:
    display(df_bookings_2026_H1[["booking_id", "tests"]].head(10))

if "test_code" in df_bookings_2026_H1.columns:
    display(df_bookings_2026_H1[["booking_id", "test_code"]].head(10))

Booking columns:
['booking_id', 'created_at', 'slot_at', 'city', 'clinic_id', 'channel', 'source', 'patient_id', 'patient_name', 'test_code', 'test_price', 'home_fee', 'patient', 'tests', 'rescheduled_from', 'status_at_export']

Sample tests values:

             booking_id tests
0  BK-PUN-202606-075346   NaN
1  BK-PUN-202606-075347   NaN
2  BK-PUN-202606-075347   NaN
3  BK-PUN-202606-075348   NaN
4  BK-PUN-202606-075348   NaN
5  BK-PUN-202606-075348   NaN
6  BK-PUN-202606-075349   NaN
7  BK-PUN-202606-075349   NaN
8  BK-PUN-202606-075349   NaN
9  BK-PUN-202606-075349   NaN

             booking_id test_code
0  BK-PUN-202606-075346      T002
1  BK-PUN-202606-075347      T006
2  BK-PUN-202606-075347      T005
3  BK-PUN-202606-075348      T007
4  BK-PUN-202606-075348      PK01
5  BK-PUN-202606-075348      T014
6  BK-PUN-202606-075349      T004
7  BK-PUN-202606-075349      T002
8  BK-PUN-202606-075349      T006
9  BK-PUN-202606-075349      PK03

In [36]:

import pandas as pd


def recover_missing_test_codes(results_df, bookings_df):
    results = results_df.copy().reset_index(drop=False)
    results = results.rename(columns={"index": "_original_index"})

    bookings = bookings_df.copy()

    # Normalize IDs and codes
    for df in (results, bookings):
        df["booking_id"] = df["booking_id"].astype("string").str.strip()
        if "test_code" in df.columns:
            df["test_code"] = df["test_code"].astype("string").str.strip()
            df["test_code"] = df["test_code"].replace("", pd.NA)

    # This function expects one booked test per row
    if "test_code" not in bookings.columns:
        raise ValueError("Bookings must contain a test_code column.")

    bookings = bookings.dropna(subset=["booking_id", "test_code"])

    # Unique codes booked under each booking
    booked_by_id = (
        bookings.groupby("booking_id")["test_code"]
        .agg(lambda s: set(s.dropna()))
        .to_dict()
    )

    # Codes already recorded in results
    recorded_by_id = (
        results.dropna(subset=["booking_id", "test_code"])
        .groupby("booking_id")["test_code"]
        .agg(lambda s: set(s.dropna()))
        .to_dict()
    )

    audit_rows = []
    missing_indices = results.index[results["test_code"].isna()].tolist()

    for idx in missing_indices:
        bid = results.at[idx, "booking_id"]

        booked = booked_by_id.get(bid, set())
        recorded = recorded_by_id.get(bid, set())
        candidates = sorted(booked - recorded)

        recovered = pd.NA

        if len(candidates) == 1:
            recovered = candidates[0]
            results.at[idx, "test_code"] = recovered

            # Update immediately to prevent reusing the same code
            recorded_by_id.setdefault(bid, set()).add(recovered)
            status = "recovered_unique_candidate"

        elif len(candidates) > 1:
            status = "ambiguous_multiple_candidates"
        elif bid not in booked_by_id:
            status = "booking_not_found_or_no_codes"
        else:
            status = "no_unrecorded_candidate"

        audit_rows.append({
            "result_index": results.at[idx, "_original_index"],
            "booking_id": bid,
            "candidate_codes": candidates,
            "recovered_test_code": recovered,
            "recovery_status": status,
        })

    # Restore original result index and columns
    results = results.set_index("_original_index")
    results.index.name = results_df.index.name

    audit = pd.DataFrame(audit_rows)

    return results, audit

df_results_2026_H1_clean, audit_2026 = recover_missing_test_codes(
    df_results_2026_H1,
    df_bookings_2026_H1
)

df_results_2025_H1_clean, audit_2025 = recover_missing_test_codes(
    df_results_2025_H1,
    df_bookings_2025_H1
)

print("2026 H1")
print(audit_2026["recovery_status"].value_counts())
print("Missing codes remaining:",
      df_results_2026_H1_clean["test_code"].isna().sum())

print("\n2025 H1")
print(audit_2025["recovery_status"].value_counts())
print("Missing codes remaining:",
      df_results_2025_H1_clean["test_code"].isna().sum())

2026 H1
recovery_status
recovered_unique_candidate       944
booking_not_found_or_no_codes    154
ambiguous_multiple_candidates     47
no_unrecorded_candidate            4
Name: count, dtype: int64
Missing codes remaining: 205

2025 H1
recovery_status
recovered_unique_candidate       1019
ambiguous_multiple_candidates      29
booking_not_found_or_no_codes       4
no_unrecorded_candidate             1
Name: count, dtype: int64
Missing codes remaining: 34

In [38]:
df_results_2026_H1_clean, audit_2026 = recover_missing_test_codes(
    df_results_2026_H1,
    df_bookings_2026_H1
)

df_results_2025_H1_clean, audit_2025 = recover_missing_test_codes(
    df_results_2025_H1,
    df_bookings_2025_H1
)

print("2026 H1")
print(audit_2026["recovery_status"].value_counts())
print("Missing codes remaining:",
      df_results_2026_H1_clean["test_code"].isna().sum())

print("\n2025 H1")
print(audit_2025["recovery_status"].value_counts())
print("Missing codes remaining:",
      df_results_2025_H1_clean["test_code"].isna().sum())

2026 H1
recovery_status
recovered_unique_candidate       944
booking_not_found_or_no_codes    154
ambiguous_multiple_candidates     47
no_unrecorded_candidate            4
Name: count, dtype: int64
Missing codes remaining: 205

2025 H1
recovery_status
recovered_unique_candidate       1019
ambiguous_multiple_candidates      29
booking_not_found_or_no_codes       4
no_unrecorded_candidate             1
Name: count, dtype: int64
Missing codes remaining: 34

In [39]:
import pandas as pd

def diagnose_null_tests(res, book, label):
    res = res.copy(); book = book.copy()
    # normalise keys so stray spaces/case don't cause false misses
    res['booking_id'] = res['booking_id'].astype(str).str.strip().str.upper()
    book['booking_id'] = book['booking_id'].astype(str).str.strip().str.upper()

    null_res = res[res['test_code'].isna()]
    print(f"--- {label} ---")
    print(f"null test_code rows: {len(null_res):,} ({len(null_res)/len(res):.3%} of results)")
    print(f"distinct booking_ids affected: {null_res['booking_id'].nunique():,}")

    # is the booking present in the bookings table at all?
    in_book = null_res['booking_id'].isin(book['booking_id'])
    print(f"found in bookings: {in_book.sum():,} | not found: {(~in_book).sum():,}")

    # how many tests does each of those bookings have?
    tests_per_booking = (book.dropna(subset=['test_code'])
                             .groupby('booking_id')['test_code'].nunique())
    print("tests per booking (for affected rows):")
    print(null_res['booking_id'].map(tests_per_booking)
                  .value_counts(dropna=False).sort_index())
    return null_res

null_2025 = diagnose_null_tests(df_results_2025_H1, df_bookings_2025_H1, "2025 H1")
null_2026 = diagnose_null_tests(df_results_2026_H1, df_bookings_2026_H1, "2026 H1")

--- 2025 H1 ---
null test_code rows: 1,053 (0.294% of results)
distinct booking_ids affected: 1,051
found in bookings: 1,049 | not found: 4
tests per booking (for affected rows):
booking_id
1.0    141
2.0    297
3.0    315
4.0    188
5.0     81
6.0     27
NaN      4
Name: count, dtype: int64
--- 2026 H1 ---
null test_code rows: 1,149 (0.304% of results)
distinct booking_ids affected: 1,145
found in bookings: 1,141 | not found: 8
tests per booking (for affected rows):
booking_id
1.0    109
2.0    307
3.0    302
4.0    183
5.0     64
6.0     30
NaN    154
Name: count, dtype: int64

In [40]:
def recover_test_codes(res, book):
    res = res.copy(); book = book.copy()
    for d in (res, book):
        d['booking_id'] = d['booking_id'].astype(str).str.strip().str.upper()

    booked = book.dropna(subset=['test_code'])[['booking_id', 'test_code']].drop_duplicates()
    done   = res.dropna(subset=['test_code'])[['booking_id', 'test_code']]

    # tests that were booked but have no result row with a code yet
    m = booked.merge(done, on=['booking_id', 'test_code'], how='left', indicator=True)
    candidates = (m[m['_merge'] == 'left_only']
                    .groupby('booking_id')['test_code'].agg(list)
                    .rename('candidates'))

    null_counts = (res[res['test_code'].isna()]
                     .groupby('booking_id').size().rename('n_null'))

    fix = pd.concat([null_counts, candidates], axis=1, join='inner')
    fix['n_cand'] = fix['candidates'].str.len()

    # safe only when exactly 1 null row and exactly 1 candidate test
    safe = fix[(fix['n_null'] == 1) & (fix['n_cand'] == 1)].copy()
    safe['test_code_fill'] = safe['candidates'].str[0]

    print(f"affected bookings: {len(null_counts):,} | safely recoverable: {len(safe):,}")

    out = res.merge(safe['test_code_fill'], left_on='booking_id',
                    right_index=True, how='left')
    mask = out['test_code'].isna() & out['test_code_fill'].notna()
    out.loc[mask, 'test_code'] = out.loc[mask, 'test_code_fill']
    out['test_code_recovered'] = mask
    return out.drop(columns='test_code_fill')

res_2025_clean = recover_test_codes(df_results_2025_H1, df_bookings_2025_H1)
print("still null:", res_2025_clean['test_code'].isna().sum())

affected bookings: 1,051 | safely recoverable: 1,019
still null: 34

In [41]:
df_bookings_2026_H1[df_bookings_2026_H1['tests'].notna()][['booking_id','city','test_code','patient','tests','status_at_export']].head(10)

,booking_id,city,test_code,patient,tests,status_at_export
0,nova_jai_0052709,Jaipur,NaN,"{'patient_id': 'PJAI0028832', 'is_new': False}","[{'code': 'T013', 'price': 400}, {'code': 'T00...",booked
1,nova_jai_0052710,Jaipur,NaN,"{'patient_id': 'PJAI0028823', 'is_new': False}","[{'code': 'T002', 'price': 120}, {'code': 'T01...",booked
2,nova_jai_0052711,Jaipur,NaN,"{'patient_id': 'PJAI0026054', 'is_new': False}","[{'code': 'T004', 'price': 650}, {'code': 'T01...",booked
3,nova_jai_0052712,Jaipur,NaN,"{'patient_id': 'PJAI0027926', 'is_new': False}","[{'code': 'T007', 'price': 550}, {'code': 'T01...",booked
4,nova_jai_0052713,Jaipur,NaN,"{'patient_id': 'PJAI0024547', 'is_new': False}","[{'code': 'T002', 'price': 120}]",booked
5,nova_jai_0052714,Jaipur,NaN,"{'patient_id': 'PJAI0025560', 'is_new': False}","[{'code': 'T001', 'price': 350}]",booked
6,nova_jai_0052715,Jaipur,NaN,"{'patient_id': 'PJAI0027367', 'is_new': False}","[{'code': 'T011', 'price': 750}, {'code': 'T01...",booked
7,nova_jai_0052716,Jaipur,NaN,"{'patient_id': 'PJAI0026351', 'is_new': False}","[{'code': 'T003', 'price': 450}, {'code': 'PK0...",booked
8,nova_jai_0052717,Jaipur,NaN,"{'patient_id': 'PJAI0028504', 'is_new': False}","[{'code': 'T016', 'price': 160}, {'code': 'T00...",booked
9,nova_jai_0052718,Jaipur,NaN,"{'patient_id': 'PJAI0025831', 'is_new': False}","[{'code': 'T019', 'price': 500}, {'code': 'T00...",booked

In [42]:
b26 = df_bookings_2026_H1.copy()

# parse robustly: mixed formats and mixed timezone offsets -> UTC
ts = pd.to_datetime(b26['created_at'], errors='coerce', utc=True, format='mixed')
print("unparseable created_at:", ts.isna().sum())
print(b26.loc[ts.isna(), 'created_at'].head(10))   # eyeball any that failed

b26['month'] = ts.dt.strftime('%Y-%m')
b26['new_fmt'] = b26['tests'].notna()

# first rows of the alternate format
print(b26.loc[b26['new_fmt'], ['booking_id','city','created_at','test_code','patient','tests','status_at_export']].head(10))

# which cities / months use the alternate format
print(b26.groupby(['city','new_fmt']).size().unstack(fill_value=0))
print(b26.groupby(['month','new_fmt']).size().unstack(fill_value=0))

unparseable created_at: 8
5440    created_at
6795    created_at
6598    created_at
6846    created_at
8464    created_at
8860    created_at
9082    created_at
7137    created_at
Name: created_at, dtype: object
         booking_id    city                 created_at test_code  \
0  nova_jai_0052709  Jaipur  2026-06-26 03:04:00+05:30       NaN
1  nova_jai_0052710  Jaipur  2026-06-05 02:57:00+05:30       NaN
2  nova_jai_0052711  Jaipur  2026-06-11 07:55:00+05:30       NaN
3  nova_jai_0052712  Jaipur  2026-06-27 09:28:00+05:30       NaN
4  nova_jai_0052713  Jaipur  2026-06-20 09:50:00+05:30       NaN
5  nova_jai_0052714  Jaipur  2026-06-16 00:38:00+05:30       NaN
6  nova_jai_0052715  Jaipur  2026-06-13 01:29:00+05:30       NaN
7  nova_jai_0052716  Jaipur  2026-06-02 07:29:00+05:30       NaN
8  nova_jai_0052717  Jaipur  2026-06-10 07:11:00+05:30       NaN
9  nova_jai_0052718  Jaipur  2026-06-18 05:30:00+05:30       NaN

                                          patient  \
0  {'patient_id': 'PJAI0028832', 'is_new': False}
1  {'patient_id': 'PJAI0028823', 'is_new': False}
2  {'patient_id': 'PJAI0026054', 'is_new': False}
3  {'patient_id': 'PJAI0027926', 'is_new': False}
4  {'patient_id': 'PJAI0024547', 'is_new': False}
5  {'patient_id': 'PJAI0025560', 'is_new': False}
6  {'patient_id': 'PJAI0027367', 'is_new': False}
7  {'patient_id': 'PJAI0026351', 'is_new': False}
8  {'patient_id': 'PJAI0028504', 'is_new': False}
9  {'patient_id': 'PJAI0025831', 'is_new': False}

                                               tests status_at_export
0  [{'code': 'T013', 'price': 400}, {'code': 'T00...           booked
1  [{'code': 'T002', 'price': 120}, {'code': 'T01...           booked
2  [{'code': 'T004', 'price': 650}, {'code': 'T01...           booked
3  [{'code': 'T007', 'price': 550}, {'code': 'T01...           booked
4                   [{'code': 'T002', 'price': 120}]           booked
5                   [{'code': 'T001', 'price': 350}]           booked
6  [{'code': 'T011', 'price': 750}, {'code': 'T01...           booked
7  [{'code': 'T003', 'price': 450}, {'code': 'PK0...           booked
8  [{'code': 'T016', 'price': 160}, {'code': 'T00...           booked
9  [{'code': 'T019', 'price': 500}, {'code': 'T00...           booked
new_fmt     False  True
city
Ahmedabad   85084      0
Bengaluru  107661      0
Chennai     41732  17621
Hyderabad   78674      0
Jaipur      20486   8922
Pune        65575      0
city            8      0
new_fmt  False  True
month
2025-12   6317      0
2026-01  61966      0
2026-02  58496      0
2026-03  58692    880
2026-04  46237   8793
2026-05  46914   8882
2026-06  41915   7988
2026-07  12876      0
2026-08  13284      0
2026-09  13251      0
2026-10  13166      0
2026-11  13094      0
2026-12  13004      0

In [43]:
# sample of raw created_at strings per format group
print(b26.groupby('new_fmt')['created_at'].apply(lambda s: s.astype(str).sample(5, random_state=1).tolist()))
print(b26['created_at'].astype(str).str.len().value_counts().head())

new_fmt
False    [30/01/2026 05:08, 16/05/2026 08:00, 29/05/202...
True     [2026-05-05 16:37:00+05:30, 2026-06-03 01:22:0...
Name: created_at, dtype: object
created_at
16    399212
25     26543
10         8
Name: count, dtype: int64

In [44]:
import ast
import pandas as pd

def drop_header_rows(df, name):
    bad = df['booking_id'].astype(str).str.strip().str.lower().eq('booking_id')
    print(f"{name}: dropping {bad.sum()} repeated header rows")
    return df[~bad].copy()

def to_obj(x):
    """tests/patient may be real python objects or their string repr"""
    if isinstance(x, (list, dict)):
        return x
    if isinstance(x, str):
        try:
            return ast.literal_eval(x)
        except Exception:
            return None
    return None

# 1. drop header rows everywhere
b25 = drop_header_rows(df_bookings_2025_H1, "bookings 2025")
b26 = drop_header_rows(df_bookings_2026_H1,    "bookings 2026")
r25 = drop_header_rows(df_results_2025_H1,     "results 2025")
r26 = drop_header_rows(df_results_2026_H1,     "results 2026")

# 2. split 2026 bookings by format
old = b26[b26['tests'].isna()].copy()
new = b26[b26['tests'].notna()].copy()

# 3. explode the new format: one row per (booking, test)
new['tests'] = new['tests'].map(to_obj)
new = new.explode('tests', ignore_index=True)
new['test_code']  = new['tests'].map(lambda d: d.get('code')  if isinstance(d, dict) else None)
new['test_price'] = new['tests'].map(lambda d: d.get('price') if isinstance(d, dict) else None)
print("new-format rows after explode:", len(new), "| null test_code:", new['test_code'].isna().sum())

# 4. one long bookings table (booking_id, test_code) for 2026
book26_long = pd.concat([old[['booking_id', 'city', 'test_code']],
                         new[['booking_id', 'city', 'test_code']]], ignore_index=True)

# 5. rerun Step 1 and recovery for 2026 (functions from before)
null_2026 = diagnose_null_tests(r26, book26_long, "2026 H1 (after explode)")
res_2026_clean = recover_test_codes(r26, book26_long)
print("still null:", res_2026_clean['test_code'].isna().sum())

# 6. re-run 2025 too, since header rows are now removed
res_2025_clean = recover_test_codes(r25, b25)
print("2025 still null:", res_2025_clean['test_code'].isna().sum())

bookings 2025: dropping 7 repeated header rows
bookings 2026: dropping 8 repeated header rows
results 2025: dropping 0 repeated header rows
results 2026: dropping 0 repeated header rows
new-format rows after explode: 62439 | null test_code: 21
--- 2026 H1 (after explode) ---
null test_code rows: 1,149 (0.304% of results)
distinct booking_ids affected: 1,145
found in bookings: 1,141 | not found: 8
tests per booking (for affected rows):
booking_id
1.0    126
2.0    352
3.0    351
4.0    207
5.0     72
6.0     33
NaN      8
Name: count, dtype: int64
affected bookings: 1,145 | safely recoverable: 1,089
still null: 60
affected bookings: 1,051 | safely recoverable: 1,019
2025 still null: 34

In [45]:
# A. date anomaly: where do the Jul-Dec rows come from?
ts = pd.to_datetime(b26['created_at'], errors='coerce', utc=True, format='mixed')
odd = b26[ts >= '2026-07-01']
print(len(odd)); print(odd.groupby('city').size())
print(odd[['booking_id', 'city', 'created_at', 'slot_at']].sample(10, random_state=1))
print(odd['created_at'].astype(str).str.len().value_counts().head())

# B. package codes: one code in your sample starts with PK
pk_book = book26_long['test_code'].astype(str).str.startswith('PK').sum()
pk_res  = r26['test_code'].astype(str).str.startswith('PK').sum()
print("PK codes in bookings:", pk_book, "| in results:", pk_res)
rec = res_2025_clean[res_2025_clean['test_code_recovered']]
print("PK among 2025 recovered fills:", rec['test_code'].astype(str).str.startswith('PK').sum())

78675
city
Ahmedabad    16982
Bengaluru    21028
Chennai       8549
Hyderabad    15332
Jaipur        3922
Pune         12862
dtype: int64
                 booking_id       city        created_at           slot_at
6056   BK-CHE-202603-084451    Chennai  07/03/2026 08:02  12/03/2026 12:00
9738   BK-CHE-202601-074040    Chennai  10/01/2026 22:27  14/01/2026 07:30
15700  BK-BLR-202601-091067  Bengaluru  09/01/2026 07:16  12/01/2026 12:59
9963   BK-CHE-202601-074132    Chennai  07/01/2026 22:36  10/01/2026 08:26
2019   BK-AHM-202606-096407  Ahmedabad  11/06/2026 21:20  16/06/2026 06:04
4412   BK-BLR-202603-102323  Bengaluru  08/03/2026 10:24  12/03/2026 18:55
9594   BK-PUN-202603-065537       Pune  10/03/2026 03:35  13/03/2026 07:28
1013   BK-PUN-202606-075792       Pune  11/06/2026 06:13  11/06/2026 06:45
13242  BK-AHM-202604-089259  Ahmedabad  09/04/2026 01:11  09/04/2026 11:07
5623   BK-BLR-202601-086778  Bengaluru  09/01/2026 02:08  11/01/2026 08:31
created_at
16    78675
Name: count, dtype: int64
PK codes in bookings: 73541 | in results: 59942
PK among 2025 recovered fills: 137

In [46]:
def parse_ts(col):
    s = col.astype(str).str.strip()
    dmy = s.str.match(r'^\d{2}/\d{2}/\d{4} \d{2}:\d{2}')
    iso = s.str.match(r'^\d{4}-\d{2}-\d{2}')
    a = pd.to_datetime(s.where(dmy), format='%d/%m/%Y %H:%M', errors='coerce')
    b = (pd.to_datetime(s.where(iso), format='ISO8601', utc=True, errors='coerce')
           .dt.tz_convert('Asia/Kolkata').dt.tz_localize(None))
    out = a.fillna(b)
    print(f"{col.name}: dd/mm/yyyy={dmy.sum():,} | ISO={iso.sum():,} | unparsed={out.isna().sum():,}")
    return out

b26['created_dt'] = parse_ts(b26['created_at'])
b26['slot_dt']    = parse_ts(b26['slot_at'])

# sanity check: old-format booking ids carry YYYYMM, e.g. BK-CHE-202603-084451
idm = b26['booking_id'].str.extract(r'-(\d{6})-')[0]
ok = idm.notna()
print("created month == booking_id month:",
      (idm[ok] == b26.loc[ok, 'created_dt'].dt.strftime('%Y%m')).mean())
print(b26['created_dt'].dt.to_period('M').value_counts().sort_index())

created_at: dd/mm/yyyy=399,212 | ISO=26,543 | unparsed=0
slot_at: dd/mm/yyyy=399,212 | ISO=26,543 | unparsed=0
created month == booking_id month: 0.9132916846186988
created_dt
2025-12     6317
2026-01    78466
2026-02    79153
2026-03    75857
2026-04    64570
2026-05    62963
2026-06    58413
2026-07       16
Freq: M, Name: count, dtype: int64

In [47]:
def norm(s): return s.astype(str).str.strip().str.upper()

def finalise(res_clean, book, year):
    out = res_clean.copy()
    out['booking_id'] = norm(out['booking_id'])
    cm = (book.assign(booking_id=norm(book['booking_id']))
              .drop_duplicates('booking_id').set_index('booking_id')['city'])
    out['city'] = out['booking_id'].map(cm)
    out['test_code'] = out['test_code'].fillna('UNKNOWN')
    out['result_dt'] = parse_ts(out['result_ts'])
    out['year'] = year
    print(year, "| rows:", len(out), "| no city:", out['city'].isna().sum(),
          "| UNKNOWN:", (out['test_code'] == 'UNKNOWN').sum())
    return out

f25 = finalise(res_2025_clean, b25, 2025)
f26 = finalise(res_2026_clean, book26_long, 2026)
allres = pd.concat([f25, f26], ignore_index=True)

print(allres.groupby(['year', allres['result_dt'].dt.month]).size().unstack(0))   # expect months 1-6 only
city = allres.groupby(['city', 'year']).size().unstack()
city['growth_pct'] = (city[2026] / city[2025] - 1) * 100
print(city.round(1))

# why the leftovers stayed null
print(classify_leftover(res_2025_clean, b25))
print(classify_leftover(res_2026_clean, book26_long))

result_ts: dd/mm/yyyy=0 | ISO=357,769 | unparsed=0
2025 | rows: 357769 | no city: 1798 | UNKNOWN: 34
result_ts: dd/mm/yyyy=0 | ISO=378,358 | unparsed=0
2026 | rows: 378358 | no city: 1922 | UNKNOWN: 60
year        2025   2026
result_dt
1          58522  62437
2          59653  66423
3          60935  63901
4          59589  61979
5          58855  60460
6          58435  61243
7           1776   1911
12             4      4
year          2025     2026  growth_pct
city
Ahmedabad  62819.0  69734.0        11.0
Bangalore  81446.0      NaN         NaN
Bengaluru      NaN  88692.0         NaN
Chennai    65256.0  66133.0         1.3
Hyderabad  59922.0  64684.0         7.9
Jaipur     36916.0  33275.0        -9.9
Pune       49612.0  53918.0         8.7

NameError: name 'classify_leftover' is not defined

In [48]:
# --- 1. harmonise city names (in place) ---
for d in (f25, f26, b25, book26_long):
    d['city'] = d['city'].str.strip().replace({'Bangalore': 'Bengaluru'})
allres = pd.concat([f25, f26], ignore_index=True)

# --- 2. is the booking_id month the slot month? ---
sm = b26['slot_dt'].dt.strftime('%Y%m')
print("slot month == booking_id month:", (idm[ok] == sm[ok]).mean())

# --- 3. orphan results (no matching booking): what are they? ---
allres['prefix'] = allres['booking_id'].str.extract(r'^([A-Z]+[-_][A-Z]+)')[0]
orph = allres[allres['city'].isna()]
print(orph.groupby('year')['prefix'].value_counts())
print(orph['booking_id'].sample(10, random_state=1).tolist())
# prefix -> city mapping learned from the matched rows
print(pd.crosstab(allres['prefix'], allres['city']))

# --- 4. is the Jaipur/Chennai gap there from January, or does it open after the switch? ---
m = allres[allres['city'].notna()].copy()
m['grp'] = m['city'].isin(['Jaipur', 'Chennai']).map({True: 'Jaipur+Chennai', False: 'Other 4'})
m['month'] = m['result_dt'].dt.month
t = m[m['month'].between(1, 6)].groupby(['grp', 'month', 'year']).size().unstack('year')
t['growth_pct'] = (t[2026] / t[2025] - 1) * 100
print(t.round(1))

# --- 5. cross-check against bookings (tests booked, not results) ---
bk = pd.concat([b25.assign(year=2025)[['city', 'year']],
                book26_long.assign(year=2026)[['city', 'year']]])
bkc = bk.groupby(['city', 'year']).size().unstack()
bkc['growth_pct'] = (bkc[2026] / bkc[2025] - 1) * 100
print(bkc.round(1))

# --- 6. leftover nulls (function wasn't defined in your session) ---
def classify_leftover(res_clean, book):
    left = res_clean[res_clean['test_code'].isna()].copy()
    left['booking_id'] = left['booking_id'].astype(str).str.strip().str.upper()
    bk_ = book.copy()
    bk_['booking_id'] = bk_['booking_id'].astype(str).str.strip().str.upper()
    has_code = set(bk_.dropna(subset=['test_code'])['booking_id'])
    exists = set(bk_['booking_id'])
    left['reason'] = 'ambiguous (multiple nulls or no single candidate)'
    left.loc[~left['booking_id'].isin(exists), 'reason'] = 'booking not found'
    left.loc[left['booking_id'].isin(exists) & ~left['booking_id'].isin(has_code), 'reason'] = 'booking has no test_code'
    return left['reason'].value_counts()

print(classify_leftover(res_2025_clean, b25))
print(classify_leftover(res_2026_clean, book26_long))

slot month == booking_id month: 1.0
year  prefix
2025  BK-BLR    397
      BK-CHE    347
      BK-AHM    333
      BK-HYD    304
      BK-PUN    222
      BK-JAI    195
2026  BK-BLR    437
      BK-AHM    365
      BK-CHE    341
      BK-HYD    337
      BK-PUN    278
      BK-JAI    164
Name: count, dtype: int64
['BK-HYD-202503-928385', 'BK-AHM-202504-921852', 'BK-BLR-202604-952849', 'BK-HYD-202506-929604', 'BK-CHE-202505-930255', 'BK-AHM-202605-942553', 'BK-JAI-202502-971654', 'BK-BLR-202501-938948', 'BK-BLR-202602-903842', 'BK-CHE-202506-949678']
city      Ahmedabad  Bengaluru  Chennai  Hyderabad  Jaipur    Pune
prefix
BK-AHM       132553          0        0          0       0       0
BK-BLR            0     170138        0          0       0       0
BK-CHE            0          0    99526          0       0       0
BK-HYD            0          0        0     124606       0       0
BK-JAI            0          0        0          0   53952       0
BK-PUN            0          0        0          0       0  103530
NOVA_CHE          0          0    31863          0       0       0
NOVA_JAI          0          0        0          0   16239       0
year                   2025   2026  growth_pct
grp            month
Jaipur+Chennai 1      16436  16399        -0.2
               2      17061  17739         4.0
               3      18201  16640        -8.6
               4      16510  16006        -3.1
               5      16788  16065        -4.3
               6      16689  16053        -3.8
Other 4        1      41796  45755         9.5
               2      42282  48343        14.3
               3      42417  46942        10.7
               4      42772  45656         6.7
               5      41771  44063         5.5
               6      41476  44872         8.2
year         2025    2026  growth_pct
city
Ahmedabad   76926   85084        10.6
Bengaluru  100070  107661         7.6
Chennai     80267   83161         3.6
Hyderabad   73237   78674         7.4
Jaipur      45149   41496        -8.1
Pune        60653   65575         8.1
reason
ambiguous (multiple nulls or no single candidate)    30
booking not found                                     4
Name: count, dtype: int64
reason
ambiguous (multiple nulls or no single candidate)    52
booking not found                                     8
Name: count, dtype: int64

In [49]:
PREFIX_CITY = {'BK-AHM': 'Ahmedabad', 'BK-BLR': 'Bengaluru', 'BK-CHE': 'Chennai',
               'BK-HYD': 'Hyderabad', 'BK-JAI': 'Jaipur', 'BK-PUN': 'Pune',
               'NOVA_CHE': 'Chennai', 'NOVA_JAI': 'Jaipur'}
allres['city_final'] = allres['city'].fillna(allres['prefix'].map(PREFIX_CITY))
print("still no city:", allres['city_final'].isna().sum())     # expect 0

# city table
ct = allres.groupby(['city_final', 'year']).size().unstack()
ct.loc['TOTAL'] = ct.sum()
ct['growth_pct'] = (ct[2026] / ct[2025] - 1) * 100
print(ct.round(1))

# Jaipur+Chennai vs the other four
allres['grp'] = allres['city_final'].isin(['Jaipur', 'Chennai']).map({True: 'Jaipur+Chennai', False: 'Other 4'})
g = allres.groupby(['grp', 'year']).size().unstack()
g['growth_pct'] = (g[2026] / g[2025] - 1) * 100
print(g.round(1))

# which tests drive the change (UNKNOWN kept out of the per-test view)
known = allres[allres['test_code'] != 'UNKNOWN']
tc = known.groupby(['test_code', 'year']).size().unstack(fill_value=0)
tc['change'] = tc[2026] - tc[2025]
tc['growth_pct'] = (tc[2026] / tc[2025].replace(0, float('nan')) - 1) * 100
tot_change = (allres['year'] == 2026).sum() - (allres['year'] == 2025).sum()
tc['pct_of_total_change'] = tc['change'] / tot_change * 100
print(tc.sort_values('change', ascending=False).head(10).round(1))
print(tc.sort_values('change').head(5).round(1))

still no city: 0
year          2025    2026  growth_pct
city_final
Ahmedabad    63152   70099        11.0
Bengaluru    81843   89129         8.9
Chennai      65603   66474         1.3
Hyderabad    60226   65021         8.0
Jaipur       37111   33439        -9.9
Pune         49834   54196         8.8
TOTAL       357769  378358         5.8
year              2025    2026  growth_pct
grp
Jaipur+Chennai  102714   99913        -2.7
Other 4         255055  278445         9.2
year        2025   2026  change  growth_pct  pct_of_total_change
test_code
PK01       16277  22211    5934        36.5                 28.8
PK02       11267  15229    3962        35.2                 19.2
PK03       11293  15080    3787        33.5                 18.4
PK04        5630   7590    1960        34.8                  9.5
T002       35841  36567     726         2.0                  3.5
T001       44593  45237     644         1.4                  3.1
T004       26670  27087     417         1.6                  2.0
T003       24334  24750     416         1.7                  2.0
T008       16446  16799     353         2.1                  1.7
T009       13655  14005     350         2.6                  1.7
year        2025   2026  change  growth_pct  pct_of_total_change
test_code
T015        8519   8430     -89        -1.0                 -0.4
T018        2858   2841     -17        -0.6                 -0.1
T010       21817  21842      25         0.1                  0.1
T012        5603   5675      72         1.3                  0.3
T005       19148  19253     105         0.5                  0.5

In [50]:
def pref(s): return norm(s).str.extract(r'^([A-Z]+[-_][A-Z]+)')[0]

jc = ['Jaipur', 'Chennai']
bk26 = book26_long[book26_long['city'].isin(jc)].assign(prefix=lambda d: pref(d['booking_id']))
r26 = allres[(allres['year'] == 2026) & allres['city_final'].isin(jc)]
cmp = pd.DataFrame({'tests_booked': bk26.groupby('prefix').size(),
                    'results': r26.groupby('prefix').size()})
cmp['results_per_booked'] = cmp['results'] / cmp['tests_booked']
print(cmp.round(3))

# new-software bookings carry a status; cancelled ones should not produce results
print(b26.loc[b26['tests'].notna(), 'status_at_export'].value_counts())

          tests_booked  results  results_per_booked
prefix
BK-CHE           41732    34611               0.829
BK-JAI           20486    17200               0.840
NOVA_CHE         41429    31863               0.769
NOVA_JAI         21010    16239               0.773
status_at_export
booked         25043
rescheduled     1500
Name: count, dtype: int64

In [51]:
# --- A. packages vs everything else: by city and by month ---
allres['is_pk']  = allres['test_code'].str.startswith('PK')
allres['rmonth'] = allres['result_dt'].dt.month

def growth(g):
    g = g.copy(); g['growth_pct'] = (g[2026] / g[2025] - 1) * 100
    return g.round(1)

print(growth(allres.groupby(['city_final', 'is_pk', 'year']).size().unstack('year')))
h1 = allres[allres['rmonth'].between(1, 6)]
print(growth(h1.groupby(['rmonth', 'is_pk', 'year']).size().unstack('year')))

# --- B. rescheduled bookings (new software only) ---
rs = b26[b26['rescheduled_from'].notna()].copy()
rs['orig'] = norm(rs['rescheduled_from'])
rs['bid']  = norm(rs['booking_id'])
all_b_ids  = set(norm(b26['booking_id']))
res_ids    = set(allres.loc[allres['year'] == 2026, 'booking_id'])

print(rs.groupby('city').size())
print("originals also present as bookings:", rs['orig'].isin(all_b_ids).mean())
print("originals that have results:       ", rs['orig'].isin(res_ids).mean())
print("rescheduled bookings with results: ", rs['bid'].isin(res_ids).mean())
print(rs[['booking_id', 'rescheduled_from', 'created_dt', 'slot_dt']].head())

year               2025   2026  growth_pct
city_final is_pk
Ahmedabad  False  55122  58790         6.7
           True    8030  11309        40.8
Bengaluru  False  71569  75121         5.0
           True   10274  14008        36.3
Chennai    False  57460  55958        -2.6
           True    8143  10516        29.1
Hyderabad  False  52925  54733         3.4
           True    7301  10288        40.9
Jaipur     False  32521  28046       -13.8
           True    4590   5393        17.5
Pune       False  43705  45600         4.3
           True    6129   8596        40.3
year           2025   2026  growth_pct
rmonth is_pk
1      False  51221  52565         2.6
       True    7301   9872        35.2
2      False  52322  55835         6.7
       True    7331  10588        44.4
3      False  53305  53798         0.9
       True    7630  10103        32.4
4      False  52262  52050        -0.4
       True    7327   9929        35.5
5      False  51468  50805        -1.3
       True    7387   9655        30.7
6      False  51155  51592         0.9
       True    7280   9651        32.6
city
Chennai    996
Jaipur     504
dtype: int64
originals also present as bookings: 1.0
originals that have results:        0.8246666666666667
rescheduled bookings with results:  0.0
            booking_id  rescheduled_from          created_dt  \
2873  nova_jai_0055582  nova_jai_0054144 2026-06-16 12:34:00
2874  nova_jai_0055583  nova_jai_0054826 2026-06-19 04:06:00
2875  nova_jai_0055584  nova_jai_0052896 2026-06-10 09:29:00
2876  nova_jai_0055585  nova_jai_0053217 2026-06-03 07:25:00
2877  nova_jai_0055586  nova_jai_0055565 2026-06-16 12:44:00

                 slot_dt
2873 2026-06-19 19:53:00
2874 2026-06-25 13:35:00
2875 2026-06-13 09:55:00
2876 2026-06-08 16:20:00
2877 2026-06-23 19:20:00

In [52]:
"""
Kalpa Health, Brief A: cleaning pipeline (results tables, H1 2025 vs H1 2026)

Run in the notebook that already holds the four raw DataFrames:

    %run kalpa_clean.py
    res, book = clean_all(df_results_2025_H1, df_results_2026_H1,
                          df_bookings_H1_2025_H1, df_bookings_2026_H1)

res  = one row per test result, both years: city, parsed result_dt, test_code
       ('UNKNOWN' if it could not be recovered), flags test_code_recovered
       and test_code_unknown
book = one row per (booking, test), both years, new-format bookings exploded

The raw inputs are never modified.
"""
import ast

import pandas as pd

CITY_FIX = {"Bangalore": "Bengaluru"}
PREFIX_CITY = {
    "BK-AHM": "Ahmedabad", "BK-BLR": "Bengaluru", "BK-CHE": "Chennai",
    "BK-HYD": "Hyderabad", "BK-JAI": "Jaipur", "BK-PUN": "Pune",
    "NOVA_CHE": "Chennai", "NOVA_JAI": "Jaipur",
}
ID_PREFIX = r"^([A-Z]+[-_][A-Z]+)"


# ---------------------------------------------------------------- helpers
def _norm_id(s):
    return s.astype(str).str.strip().str.upper()


def _norm_code(s):
    return s.str.strip().str.upper()          # keeps NaN as NaN


def _to_obj(x):
    """`tests` may be a real python list or its string repr."""
    if isinstance(x, (list, dict)):
        return x
    if isinstance(x, str):
        try:
            return ast.literal_eval(x)
        except Exception:
            return None
    return None


def drop_header_rows(df, name):
    """Repeated header rows left over from concatenating the city files."""
    bad = df["booking_id"].astype(str).str.strip().str.lower().eq("booking_id")
    print(f"{name}: dropped {bad.sum()} repeated header rows")
    return df[~bad].copy()


def parse_ts(col):
    """Two formats coexist: ISO with +05:30 offset, and day-first dd/mm/yyyy HH:MM.
    Both end up as naive IST datetimes."""
    s = col.astype(str).str.strip()
    dmy = s.str.match(r"^\d{2}/\d{2}/\d{4} \d{2}:\d{2}")
    iso = s.str.match(r"^\d{4}-\d{2}-\d{2}")
    a = pd.to_datetime(s.where(dmy), format="%d/%m/%Y %H:%M", errors="coerce")
    b = (pd.to_datetime(s.where(iso), format="ISO8601", utc=True, errors="coerce")
           .dt.tz_convert("Asia/Kolkata").dt.tz_localize(None))
    out = a.fillna(b)
    print(f"  {col.name}: dd/mm/yyyy={dmy.sum():,} | ISO={iso.sum():,} | unparsed={out.isna().sum():,}")
    return out


# --------------------------------------------------------------- bookings
def _explode_new_format(b):
    """New booking software (Jaipur/Chennai): one row per booking with a `tests`
    list of {'code', 'price'} -> one row per test, like the old format."""
    is_new = b["tests"].notna()
    old, new = b[~is_new].copy(), b[is_new].copy()
    new["tests"] = new["tests"].map(_to_obj)
    new = new.explode("tests", ignore_index=True)
    new["test_code"] = new["tests"].map(lambda d: d.get("code") if isinstance(d, dict) else None)
    new["test_price"] = new["tests"].map(lambda d: d.get("price") if isinstance(d, dict) else None)
    return pd.concat([old, new], ignore_index=True)


def prep_bookings(raw, year):
    b = drop_header_rows(raw, f"bookings {year}")
    if "tests" in b.columns:
        b = _explode_new_format(b)
    if "rescheduled_from" not in b.columns:
        b["rescheduled_from"] = pd.Series([None] * len(b), index=b.index, dtype="object")
    return pd.DataFrame({
        "booking_id": _norm_id(b["booking_id"]),
        "city": b["city"].str.strip().replace(CITY_FIX),
        "test_code": _norm_code(b["test_code"]),
        "test_price": b["test_price"],
        "created_dt": parse_ts(b["created_at"]),
        "slot_dt": parse_ts(b["slot_at"]),
        "rescheduled_from": b["rescheduled_from"].astype("object").str.strip().str.upper(),
        "year": year,
    })


# ---------------------------------------------------------------- results
def recover_test_codes(res, book):
    """Fill a null test_code from the booking: booked tests that have no coded result
    row yet are the candidates. Fill only when exactly 1 null row and exactly 1
    candidate exist for that booking, so a fill can never create a duplicate pair."""
    booked = book.dropna(subset=["test_code"])[["booking_id", "test_code"]].drop_duplicates()
    done = res.dropna(subset=["test_code"])[["booking_id", "test_code"]]
    m = booked.merge(done, on=["booking_id", "test_code"], how="left", indicator=True)
    cand = (m[m["_merge"] == "left_only"]
            .groupby("booking_id")["test_code"].agg(list).rename("candidates"))
    n_null = res[res["test_code"].isna()].groupby("booking_id").size().rename("n_null")

    fix = pd.concat([n_null, cand], axis=1, join="inner")
    fix["n_cand"] = fix["candidates"].str.len()
    safe = fix[(fix["n_null"] == 1) & (fix["n_cand"] == 1)].copy()
    safe["fill"] = safe["candidates"].str[0]

    out = res.merge(safe["fill"], left_on="booking_id", right_index=True, how="left")
    mask = out["test_code"].isna() & out["fill"].notna()
    out.loc[mask, "test_code"] = out.loc[mask, "fill"]
    out["test_code_recovered"] = mask
    print(f"  null test_code: {len(res) - len(res.dropna(subset=['test_code'])):,} | "
          f"recovered: {int(mask.sum()):,} | still null: {int(out['test_code'].isna().sum()):,}")
    return out.drop(columns="fill")


def prep_results(raw, book, year):
    r = drop_header_rows(raw, f"results {year}")
    r["booking_id"] = _norm_id(r["booking_id"])
    r["test_code"] = _norm_code(r["test_code"])
    r = recover_test_codes(r, book)
    r["test_code_unknown"] = r["test_code"].isna()
    r["test_code"] = r["test_code"].fillna("UNKNOWN")

    # city: from the booking if it exists, otherwise from the booking_id prefix
    r["prefix"] = r["booking_id"].str.extract(ID_PREFIX)[0]
    city_map = book.drop_duplicates("booking_id").set_index("booking_id")["city"]
    r["city"] = r["booking_id"].map(city_map).fillna(r["prefix"].map(PREFIX_CITY))

    r["result_dt"] = parse_ts(r["result_ts"])
    r["year"] = year
    return r


# --------------------------------------------------------------------- QA
def qa_report(res, book):
    print("\n================ QA REPORT ================")
    print(res.groupby("year").agg(
        rows=("booking_id", "size"),
        recovered=("test_code_recovered", "sum"),
        unknown=("test_code_unknown", "sum"),
        no_city=("city", lambda s: int(s.isna().sum()))))

    print("\nresult months (expect mostly 1-6):")
    print(res.groupby(["year", res["result_dt"].dt.month]).size().unstack(0))

    ct = res.groupby(["city", "year"]).size().unstack()
    ct.loc["TOTAL"] = ct.sum()
    ct["growth_pct"] = (ct[2026] / ct[2025] - 1) * 100
    print("\nresults by city:")
    print(ct.round(1))

    pk = res["test_code"].str.startswith("PK").rename("is_package")
    pt = res.groupby([pk, "year"]).size().unstack()
    pt["growth_pct"] = (pt[2026] / pt[2025] - 1) * 100
    print("\npackages vs other tests:")
    print(pt.round(1))

    # bookings side; rescheduled bookings get a new id with no results, so remove them
    resched = book.loc[book["rescheduled_from"].notna(), "booking_id"].unique()
    book_adj = book[~book["booking_id"].isin(resched)]
    bk = book.groupby(["city", "year"]).size().unstack()
    bka = book_adj.groupby(["city", "year"]).size().unstack()
    rr = res.groupby(["city", "year"]).size().unstack()
    chk = pd.DataFrame({
        "booked_growth": (bk[2026] / bk[2025] - 1) * 100,
        "booked_excl_resched_growth": (bka[2026] / bka[2025] - 1) * 100,
        "results_growth": (rr[2026] / rr[2025] - 1) * 100,
        "results_per_booked_2026": rr[2026] / bka[2026],
    })
    print("\nbookings vs results (rescheduled duplicates removed from bookings):")
    print(chk.round(3))


# ------------------------------------------------------------------- main
def clean_all(results_2025, results_2026, bookings_2025, bookings_2026):
    book25 = prep_bookings(bookings_2025, 2025)
    book26 = prep_bookings(bookings_2026, 2026)
    res25 = prep_results(results_2025, book25, 2025)
    res26 = prep_results(results_2026, book26, 2026)
    res = pd.concat([res25, res26], ignore_index=True)
    book = pd.concat([book25, book26], ignore_index=True)
    qa_report(res, book)
    return res, book

In [53]:
res, book = clean_all(df_results_2025_H1, df_results_2026_H1,
                      df_bookings_2025_H1, df_bookings_2026_H1)

bookings 2025: dropped 7 repeated header rows
  created_at: dd/mm/yyyy=436,302 | ISO=0 | unparsed=0
  slot_at: dd/mm/yyyy=436,302 | ISO=0 | unparsed=0
bookings 2026: dropped 8 repeated header rows
  created_at: dd/mm/yyyy=399,212 | ISO=62,439 | unparsed=0
  slot_at: dd/mm/yyyy=399,212 | ISO=62,439 | unparsed=0
results 2025: dropped 0 repeated header rows
  null test_code: 1,053 | recovered: 1,019 | still null: 34
  result_ts: dd/mm/yyyy=0 | ISO=357,769 | unparsed=0
results 2026: dropped 0 repeated header rows
  null test_code: 1,149 | recovered: 1,089 | still null: 60
  result_ts: dd/mm/yyyy=0 | ISO=378,358 | unparsed=0

================ QA REPORT ================
        rows  recovered  unknown  no_city
year
2025  357769       1019       34        0
2026  378358       1089       60        0

result months (expect mostly 1-6):
year        2025   2026
result_dt
1          58522  62437
2          59653  66423
3          60935  63901
4          59589  61979
5          58855  60460
6          58435  61243
7           1776   1911
12             4      4

results by city:
year         2025    2026  growth_pct
city
Ahmedabad   63152   70099        11.0
Bengaluru   81843   89129         8.9
Chennai     65603   66474         1.3
Hyderabad   60226   65021         8.0
Jaipur      37111   33439        -9.9
Pune        49834   54196         8.8
TOTAL      357769  378358         5.8

packages vs other tests:
year          2025    2026  growth_pct
is_package
False       313302  318248         1.6
True         44467   60110        35.2

bookings vs results (rescheduled duplicates removed from bookings):
           booked_growth  booked_excl_resched_growth  results_growth  \
city
Ahmedabad         10.605                      10.605          11.000
Bengaluru          7.586                       7.586           8.902
Chennai            3.605                       0.700           1.328
Hyderabad          7.424                       7.424           7.962
Jaipur            -8.091                     -10.771          -9.895
Pune               8.115                       8.115           8.753

           results_per_booked_2026
city
Ahmedabad                    0.824
Bengaluru                    0.828
Chennai                      0.822
Hyderabad                    0.826
Jaipur                       0.830
Pune                         0.826

In [54]:
def growth_tree(b, r, by):
    d = pd.concat({
        "bookings": b.groupby([by, "year"])["booking_id"].nunique(),
        "booked_rows": b.groupby([by, "year"]).size(),
        "results": r.groupby([by, "year"]).size(),
    }, axis=1).unstack("year")
    g = pd.DataFrame({
        "bookings": d["bookings"][2026] / d["bookings"][2025],
        "tests_per_booking": (d["booked_rows"][2026] / d["bookings"][2026])
                             / (d["booked_rows"][2025] / d["bookings"][2025]),
        "results_per_test_booked": (d["results"][2026] / d["booked_rows"][2026])
                                   / (d["results"][2025] / d["booked_rows"][2025]),
    })
    g["product"] = g.prod(axis=1)
    g["actual"] = d["results"][2026] / d["results"][2025]
    out = ((g - 1) * 100).round(2)                      # growth in % per branch
    out["gap_pp"] = (100 * (g["product"] - g["actual"])).round(4)   # must be 0
    return out

resched = book.loc[book["rescheduled_from"].notna(), "booking_id"].unique()
b = book[~book["booking_id"].isin(resched)]

print(growth_tree(b.assign(all="ALL"), res.assign(all="ALL"), "all"))   # overall
print(growth_tree(b, res, "city"))                                      # per city

     bookings  tests_per_booking  results_per_test_booked  product  actual  \
all
ALL      2.74               2.19                     0.72     5.75    5.75

     gap_pp
all
ALL     0.0
           bookings  tests_per_booking  results_per_test_booked  product  \
city
Ahmedabad      8.56               1.88                     0.36    11.00
Bengaluru      4.68               2.78                     1.22     8.90
Chennai       -1.98               2.73                     0.62     1.33
Hyderabad      5.44               1.88                     0.50     7.96
Jaipur       -12.29               1.73                     0.98    -9.89
Pune           6.36               1.65                     0.59     8.75

           actual  gap_pp
city
Ahmedabad   11.00     0.0
Bengaluru    8.90     0.0
Chennai      1.33     0.0
Hyderabad    7.96     0.0
Jaipur      -9.89    -0.0
Pune         8.75     0.0

In [55]:
"""
Kalpa Health, Brief A: cleaning pipeline (results tables, H1 2025 vs H1 2026)

Run in the notebook that already holds the four raw DataFrames:

    %run kalpa_clean.py
    res, book = clean_all(df_results_2025_H1, df_results_2026_H1,
                          df_bookings_H1_2025_H1, df_bookings_2026_H1)

res  = one row per test result, both years: city, parsed result_dt, test_code
       ('UNKNOWN' if it could not be recovered), flags test_code_recovered
       and test_code_unknown
book = one row per (booking, test), both years, new-format bookings exploded

The raw inputs are never modified.
"""
import ast

import pandas as pd

CITY_FIX = {"Bangalore": "Bengaluru"}
PREFIX_CITY = {
    "BK-AHM": "Ahmedabad", "BK-BLR": "Bengaluru", "BK-CHE": "Chennai",
    "BK-HYD": "Hyderabad", "BK-JAI": "Jaipur", "BK-PUN": "Pune",
    "NOVA_CHE": "Chennai", "NOVA_JAI": "Jaipur",
}
ID_PREFIX = r"^([A-Z]+[-_][A-Z]+)"


# ---------------------------------------------------------------- helpers
def _norm_id(s):
    return s.astype(str).str.strip().str.upper()


def _norm_code(s):
    return s.str.strip().str.upper()          # keeps NaN as NaN


def _to_obj(x):
    """`tests` may be a real python list or its string repr."""
    if isinstance(x, (list, dict)):
        return x
    if isinstance(x, str):
        try:
            return ast.literal_eval(x)
        except Exception:
            return None
    return None


def drop_header_rows(df, name):
    """Repeated header rows left over from concatenating the city files."""
    bad = df["booking_id"].astype(str).str.strip().str.lower().eq("booking_id")
    print(f"{name}: dropped {bad.sum()} repeated header rows")
    return df[~bad].copy()


def parse_ts(col):
    """Two formats coexist: ISO with +05:30 offset, and day-first dd/mm/yyyy HH:MM.
    Both end up as naive IST datetimes."""
    s = col.astype(str).str.strip()
    dmy = s.str.match(r"^\d{2}/\d{2}/\d{4} \d{2}:\d{2}")
    iso = s.str.match(r"^\d{4}-\d{2}-\d{2}")
    a = pd.to_datetime(s.where(dmy), format="%d/%m/%Y %H:%M", errors="coerce")
    b = (pd.to_datetime(s.where(iso), format="ISO8601", utc=True, errors="coerce")
           .dt.tz_convert("Asia/Kolkata").dt.tz_localize(None))
    out = a.fillna(b)
    print(f"  {col.name}: dd/mm/yyyy={dmy.sum():,} | ISO={iso.sum():,} | unparsed={out.isna().sum():,}")
    return out


# --------------------------------------------------------------- bookings
def _explode_new_format(b):
    """New booking software (Jaipur/Chennai): one row per booking with a `tests`
    list of {'code', 'price'} -> one row per test, like the old format."""
    is_new = b["tests"].notna()
    old, new = b[~is_new].copy(), b[is_new].copy()
    new["tests"] = new["tests"].map(_to_obj)
    new = new.explode("tests", ignore_index=True)
    new["test_code"] = new["tests"].map(lambda d: d.get("code") if isinstance(d, dict) else None)
    new["test_price"] = new["tests"].map(lambda d: d.get("price") if isinstance(d, dict) else None)
    # the new software nests the patient: {'patient_id': ..., 'is_new': ...}
    pat = new["patient"].map(_to_obj)
    new["patient_id"] = pat.map(lambda d: d.get("patient_id") if isinstance(d, dict) else None)
    new["is_new_patient"] = pat.map(lambda d: d.get("is_new") if isinstance(d, dict) else None)
    return pd.concat([old, new], ignore_index=True)


def prep_bookings(raw, year):
    b = drop_header_rows(raw, f"bookings {year}")
    if "tests" in b.columns:
        b = _explode_new_format(b)
    if "rescheduled_from" not in b.columns:
        b["rescheduled_from"] = pd.Series([None] * len(b), index=b.index, dtype="object")
    return pd.DataFrame({
        "booking_id": _norm_id(b["booking_id"]),
        "patient_id": _norm_code(b["patient_id"]),
        "is_new_patient": b["is_new_patient"] if "is_new_patient" in b.columns else None,
        "city": b["city"].str.strip().replace(CITY_FIX),
        "test_code": _norm_code(b["test_code"]),
        "test_price": b["test_price"],
        "created_dt": parse_ts(b["created_at"]),
        "slot_dt": parse_ts(b["slot_at"]),
        "rescheduled_from": b["rescheduled_from"].astype("object").str.strip().str.upper(),
        "year": year,
    })


# ---------------------------------------------------------------- results
def recover_test_codes(res, book):
    """Fill a null test_code from the booking: booked tests that have no coded result
    row yet are the candidates. Fill only when exactly 1 null row and exactly 1
    candidate exist for that booking, so a fill can never create a duplicate pair."""
    booked = book.dropna(subset=["test_code"])[["booking_id", "test_code"]].drop_duplicates()
    done = res.dropna(subset=["test_code"])[["booking_id", "test_code"]]
    m = booked.merge(done, on=["booking_id", "test_code"], how="left", indicator=True)
    cand = (m[m["_merge"] == "left_only"]
            .groupby("booking_id")["test_code"].agg(list).rename("candidates"))
    n_null = res[res["test_code"].isna()].groupby("booking_id").size().rename("n_null")

    fix = pd.concat([n_null, cand], axis=1, join="inner")
    fix["n_cand"] = fix["candidates"].str.len()
    safe = fix[(fix["n_null"] == 1) & (fix["n_cand"] == 1)].copy()
    safe["fill"] = safe["candidates"].str[0]

    out = res.merge(safe["fill"], left_on="booking_id", right_index=True, how="left")
    mask = out["test_code"].isna() & out["fill"].notna()
    out.loc[mask, "test_code"] = out.loc[mask, "fill"]
    out["test_code_recovered"] = mask
    print(f"  null test_code: {len(res) - len(res.dropna(subset=['test_code'])):,} | "
          f"recovered: {int(mask.sum()):,} | still null: {int(out['test_code'].isna().sum()):,}")
    return out.drop(columns="fill")


def prep_results(raw, book, year):
    r = drop_header_rows(raw, f"results {year}")
    r["booking_id"] = _norm_id(r["booking_id"])
    r["test_code"] = _norm_code(r["test_code"])
    r = recover_test_codes(r, book)
    r["test_code_unknown"] = r["test_code"].isna()
    r["test_code"] = r["test_code"].fillna("UNKNOWN")

    # city: from the booking if it exists, otherwise from the booking_id prefix
    r["prefix"] = r["booking_id"].str.extract(ID_PREFIX)[0]
    city_map = book.drop_duplicates("booking_id").set_index("booking_id")["city"]
    r["city"] = r["booking_id"].map(city_map).fillna(r["prefix"].map(PREFIX_CITY))

    r["result_dt"] = parse_ts(r["result_ts"])
    r["year"] = year
    return r


# --------------------------------------------------------------------- QA
def qa_report(res, book):
    print("\n================ QA REPORT ================")
    print(res.groupby("year").agg(
        rows=("booking_id", "size"),
        recovered=("test_code_recovered", "sum"),
        unknown=("test_code_unknown", "sum"),
        no_city=("city", lambda s: int(s.isna().sum()))))

    print("\nbookings rows with no patient_id (expect 0):", int(book["patient_id"].isna().sum()))

    print("\nresult months (expect mostly 1-6):")
    print(res.groupby(["year", res["result_dt"].dt.month]).size().unstack(0))

    ct = res.groupby(["city", "year"]).size().unstack()
    ct.loc["TOTAL"] = ct.sum()
    ct["growth_pct"] = (ct[2026] / ct[2025] - 1) * 100
    print("\nresults by city:")
    print(ct.round(1))

    pk = res["test_code"].str.startswith("PK").rename("is_package")
    pt = res.groupby([pk, "year"]).size().unstack()
    pt["growth_pct"] = (pt[2026] / pt[2025] - 1) * 100
    print("\npackages vs other tests:")
    print(pt.round(1))

    # bookings side; rescheduled bookings get a new id with no results, so remove them
    resched = book.loc[book["rescheduled_from"].notna(), "booking_id"].unique()
    book_adj = book[~book["booking_id"].isin(resched)]
    bk = book.groupby(["city", "year"]).size().unstack()
    bka = book_adj.groupby(["city", "year"]).size().unstack()
    rr = res.groupby(["city", "year"]).size().unstack()
    chk = pd.DataFrame({
        "booked_growth": (bk[2026] / bk[2025] - 1) * 100,
        "booked_excl_resched_growth": (bka[2026] / bka[2025] - 1) * 100,
        "results_growth": (rr[2026] / rr[2025] - 1) * 100,
        "results_per_booked_2026": rr[2026] / bka[2026],
    })
    print("\nbookings vs results (rescheduled duplicates removed from bookings):")
    print(chk.round(3))


# ------------------------------------------------------------------- main
def clean_all(results_2025, results_2026, bookings_2025, bookings_2026):
    book25 = prep_bookings(bookings_2025, 2025)
    book26 = prep_bookings(bookings_2026, 2026)
    res25 = prep_results(results_2025, book25, 2025)
    res26 = prep_results(results_2026, book26, 2026)
    res = pd.concat([res25, res26], ignore_index=True)
    book = pd.concat([book25, book26], ignore_index=True)
    qa_report(res, book)
    return res, book

In [56]:
"""
Kalpa Health, Brief A: cleaning pipeline (results tables, H1 2025 vs H1 2026)

Run in the notebook that already holds the four raw DataFrames:

    %run kalpa_clean.py
    res, book = clean_all(df_results_2025_H1, df_results_2026_H1,
                          df_bookings_H1_2025_H1, df_bookings_2026_H1)

res  = one row per test result, both years: city, parsed result_dt, test_code
       ('UNKNOWN' if it could not be recovered), flags test_code_recovered
       and test_code_unknown
book = one row per (booking, test), both years, new-format bookings exploded

The raw inputs are never modified.
"""
import ast

import pandas as pd

CITY_FIX = {"Bangalore": "Bengaluru"}
PREFIX_CITY = {
    "BK-AHM": "Ahmedabad", "BK-BLR": "Bengaluru", "BK-CHE": "Chennai",
    "BK-HYD": "Hyderabad", "BK-JAI": "Jaipur", "BK-PUN": "Pune",
    "NOVA_CHE": "Chennai", "NOVA_JAI": "Jaipur",
}
ID_PREFIX = r"^([A-Z]+[-_][A-Z]+)"


# ---------------------------------------------------------------- helpers
def _norm_id(s):
    return s.astype(str).str.strip().str.upper()


def _norm_code(s):
    return s.str.strip().str.upper()          # keeps NaN as NaN


def _to_obj(x):
    """`tests` may be a real python list or its string repr."""
    if isinstance(x, (list, dict)):
        return x
    if isinstance(x, str):
        try:
            return ast.literal_eval(x)
        except Exception:
            return None
    return None


def drop_header_rows(df, name):
    """Repeated header rows left over from concatenating the city files."""
    bad = df["booking_id"].astype(str).str.strip().str.lower().eq("booking_id")
    print(f"{name}: dropped {bad.sum()} repeated header rows")
    return df[~bad].copy()


def parse_ts(col):
    """Two formats coexist: ISO with +05:30 offset, and day-first dd/mm/yyyy HH:MM.
    Both end up as naive IST datetimes."""
    s = col.astype(str).str.strip()
    dmy = s.str.match(r"^\d{2}/\d{2}/\d{4} \d{2}:\d{2}")
    iso = s.str.match(r"^\d{4}-\d{2}-\d{2}")
    a = pd.to_datetime(s.where(dmy), format="%d/%m/%Y %H:%M", errors="coerce")
    b = (pd.to_datetime(s.where(iso), format="ISO8601", utc=True, errors="coerce")
           .dt.tz_convert("Asia/Kolkata").dt.tz_localize(None))
    out = a.fillna(b)
    print(f"  {col.name}: dd/mm/yyyy={dmy.sum():,} | ISO={iso.sum():,} | unparsed={out.isna().sum():,}")
    return out


# --------------------------------------------------------------- bookings
def _explode_new_format(b):
    """New booking software (Jaipur/Chennai): one row per booking with a `tests`
    list of {'code', 'price'} -> one row per test, like the old format."""
    is_new = b["tests"].notna()
    old, new = b[~is_new].copy(), b[is_new].copy()
    new["tests"] = new["tests"].map(_to_obj)
    new = new.explode("tests", ignore_index=True)
    new["test_code"] = new["tests"].map(lambda d: d.get("code") if isinstance(d, dict) else None)
    new["test_price"] = new["tests"].map(lambda d: d.get("price") if isinstance(d, dict) else None)
    # the new software nests the patient: {'patient_id': ..., 'is_new': ...}
    pat = new["patient"].map(_to_obj)
    new["patient_id"] = pat.map(lambda d: d.get("patient_id") if isinstance(d, dict) else None)
    new["is_new_patient"] = pat.map(lambda d: d.get("is_new") if isinstance(d, dict) else None)
    return pd.concat([old, new], ignore_index=True)


def prep_bookings(raw, year):
    b = drop_header_rows(raw, f"bookings {year}")
    if "tests" in b.columns:
        b = _explode_new_format(b)
    if "rescheduled_from" not in b.columns:
        b["rescheduled_from"] = pd.Series([None] * len(b), index=b.index, dtype="object")
    return pd.DataFrame({
        "booking_id": _norm_id(b["booking_id"]),
        "patient_id": _norm_code(b["patient_id"]),
        "is_new_patient": b["is_new_patient"] if "is_new_patient" in b.columns else None,
        "city": b["city"].str.strip().replace(CITY_FIX),
        "channel": b["channel"].astype(str).str.strip().str.lower(),
        "test_code": _norm_code(b["test_code"]),
        "test_price": b["test_price"],
        "created_dt": parse_ts(b["created_at"]),
        "slot_dt": parse_ts(b["slot_at"]),
        "rescheduled_from": b["rescheduled_from"].astype("object").str.strip().str.upper(),
        "year": year,
    })


# ---------------------------------------------------------------- results
def recover_test_codes(res, book):
    """Fill a null test_code from the booking: booked tests that have no coded result
    row yet are the candidates. Fill only when exactly 1 null row and exactly 1
    candidate exist for that booking, so a fill can never create a duplicate pair."""
    booked = book.dropna(subset=["test_code"])[["booking_id", "test_code"]].drop_duplicates()
    done = res.dropna(subset=["test_code"])[["booking_id", "test_code"]]
    m = booked.merge(done, on=["booking_id", "test_code"], how="left", indicator=True)
    cand = (m[m["_merge"] == "left_only"]
            .groupby("booking_id")["test_code"].agg(list).rename("candidates"))
    n_null = res[res["test_code"].isna()].groupby("booking_id").size().rename("n_null")

    fix = pd.concat([n_null, cand], axis=1, join="inner")
    fix["n_cand"] = fix["candidates"].str.len()
    safe = fix[(fix["n_null"] == 1) & (fix["n_cand"] == 1)].copy()
    safe["fill"] = safe["candidates"].str[0]

    out = res.merge(safe["fill"], left_on="booking_id", right_index=True, how="left")
    mask = out["test_code"].isna() & out["fill"].notna()
    out.loc[mask, "test_code"] = out.loc[mask, "fill"]
    out["test_code_recovered"] = mask
    print(f"  null test_code: {len(res) - len(res.dropna(subset=['test_code'])):,} | "
          f"recovered: {int(mask.sum()):,} | still null: {int(out['test_code'].isna().sum()):,}")
    return out.drop(columns="fill")


def prep_results(raw, book, year):
    r = drop_header_rows(raw, f"results {year}")
    r["booking_id"] = _norm_id(r["booking_id"])
    r["test_code"] = _norm_code(r["test_code"])
    r = recover_test_codes(r, book)
    r["test_code_unknown"] = r["test_code"].isna()
    r["test_code"] = r["test_code"].fillna("UNKNOWN")

    # city: from the booking if it exists, otherwise from the booking_id prefix
    r["prefix"] = r["booking_id"].str.extract(ID_PREFIX)[0]
    city_map = book.drop_duplicates("booking_id").set_index("booking_id")["city"]
    r["city"] = r["booking_id"].map(city_map).fillna(r["prefix"].map(PREFIX_CITY))
    chan_map = book.drop_duplicates("booking_id").set_index("booking_id")["channel"]
    r["channel"] = r["booking_id"].map(chan_map)          # NaN = result has no booking

    r["result_dt"] = parse_ts(r["result_ts"])
    r["year"] = year
    return r


# --------------------------------------------------------------------- QA
def qa_report(res, book):
    print("\n================ QA REPORT ================")
    print(res.groupby("year").agg(
        rows=("booking_id", "size"),
        recovered=("test_code_recovered", "sum"),
        unknown=("test_code_unknown", "sum"),
        no_city=("city", lambda s: int(s.isna().sum()))))

    print("\nbookings rows with no patient_id (expect 0):", int(book["patient_id"].isna().sum()))

    print("\nchannel values (check for spelling variants between years):")
    print(book.drop_duplicates("booking_id").groupby(["channel", "year"]).size().unstack(fill_value=0))
    print("results with no booking (no channel):", int(res["channel"].isna().sum()))

    print("\nresult months (expect mostly 1-6):")
    print(res.groupby(["year", res["result_dt"].dt.month]).size().unstack(0))

    ct = res.groupby(["city", "year"]).size().unstack()
    ct.loc["TOTAL"] = ct.sum()
    ct["growth_pct"] = (ct[2026] / ct[2025] - 1) * 100
    print("\nresults by city:")
    print(ct.round(1))

    pk = res["test_code"].str.startswith("PK").rename("is_package")
    pt = res.groupby([pk, "year"]).size().unstack()
    pt["growth_pct"] = (pt[2026] / pt[2025] - 1) * 100
    print("\npackages vs other tests:")
    print(pt.round(1))

    # bookings side; rescheduled bookings get a new id with no results, so remove them
    resched = book.loc[book["rescheduled_from"].notna(), "booking_id"].unique()
    book_adj = book[~book["booking_id"].isin(resched)]
    bk = book.groupby(["city", "year"]).size().unstack()
    bka = book_adj.groupby(["city", "year"]).size().unstack()
    rr = res.groupby(["city", "year"]).size().unstack()
    chk = pd.DataFrame({
        "booked_growth": (bk[2026] / bk[2025] - 1) * 100,
        "booked_excl_resched_growth": (bka[2026] / bka[2025] - 1) * 100,
        "results_growth": (rr[2026] / rr[2025] - 1) * 100,
        "results_per_booked_2026": rr[2026] / bka[2026],
    })
    print("\nbookings vs results (rescheduled duplicates removed from bookings):")
    print(chk.round(3))


# ------------------------------------------------------------------- main
def clean_all(results_2025, results_2026, bookings_2025, bookings_2026):
    book25 = prep_bookings(bookings_2025, 2025)
    book26 = prep_bookings(bookings_2026, 2026)
    res25 = prep_results(results_2025, book25, 2025)
    res26 = prep_results(results_2026, book26, 2026)
    res = pd.concat([res25, res26], ignore_index=True)
    book = pd.concat([book25, book26], ignore_index=True)
    qa_report(res, book)
    show_growth_trees(book, res)
    return res, book


# ------------------------------------------------------------ growth tree
BRANCHES = ["patients", "visits_per_patient", "tests_per_visit", "results_per_test_booked"]


def growth_tree(book, res, by=None):
    """Results = patients x visits/patient x tests/visit x results/test booked.
    visit = booking. Rescheduled duplicate bookings are removed first (they never get results).
    The four branch growth rates multiply back to the actual growth in results; gap_pp must be 0.

    by = None | 'city' | 'channel' | ['city', 'channel'] -> one tree per segment.
    Results with no matching booking have no channel, so channel splits use matched results
    only; the overall tree (by=None) uses all results."""
    resched = book.loc[book["rescheduled_from"].notna(), "booking_id"].unique()
    b = book[~book["booking_id"].isin(resched)]
    keys = [by] if isinstance(by, str) else list(by or [])
    if not keys:
        b, res = b.assign(_all="ALL"), res.assign(_all="ALL")
        keys = ["_all"]
    else:
        res = res.dropna(subset=keys)

    d = pd.concat({
        "patients": b.groupby(keys + ["year"])["patient_id"].nunique(),
        "visits": b.groupby(keys + ["year"])["booking_id"].nunique(),
        "rows": b.groupby(keys + ["year"]).size(),
        "results": res.groupby(keys + ["year"]).size(),
    }, axis=1).unstack("year")

    def ratio(num, den):
        return (d[num][2026] / d[den][2026]) / (d[num][2025] / d[den][2025])

    g = pd.DataFrame({
        "patients": d["patients"][2026] / d["patients"][2025],
        "visits_per_patient": ratio("visits", "patients"),
        "tests_per_visit": ratio("rows", "visits"),
        "results_per_test_booked": ratio("results", "rows"),
    })
    g["product"] = g.prod(axis=1)
    g["actual"] = d["results"][2026] / d["results"][2025]
    out = ((g - 1) * 100).round(2)
    out["gap_pp"] = (100 * (g["product"] - g["actual"])).round(4)
    out["results_2025"] = d["results"][2025]
    out["results_2026"] = d["results"][2026]
    out.index.names = keys if keys != ["_all"] else ["overall"]
    return out


def contribution(res, by):
    """Additive split: each segment's contribution (percentage points) to total growth.
    Contributions sum to the overall growth. Uses all results; unmatched ones show as NaN."""
    keys = [by] if isinstance(by, str) else list(by)
    t = res.groupby(keys + ["year"], dropna=False).size().unstack("year").fillna(0)
    total25 = t[2025].sum()
    t["growth_pct"] = (t[2026] / t[2025].replace(0, float("nan")) - 1) * 100
    t["contribution_pp"] = (t[2026] - t[2025]) / total25 * 100
    total = pd.DataFrame([[t[2025].sum(), t[2026].sum(), (t[2026].sum() / total25 - 1) * 100,
                           t["contribution_pp"].sum()]], columns=t.columns)
    total.index = (pd.MultiIndex.from_tuples([("TOTAL",) + ("",) * (len(keys) - 1)], names=keys)
                   if len(keys) > 1 else pd.Index(["TOTAL"], name=keys[0]))
    t = pd.concat([t, total])
    return t.round(2)


def show_growth_trees(book, res):
    pd.set_option("display.width", 200)
    pd.set_option("display.max_columns", 20)
    print("\n================ GROWTH TREE: overall ================")
    print(growth_tree(book, res).T)
    for by in ("city", "channel", ["city", "channel"]):
        print(f"\n================ GROWTH TREE by {by} (growth %, gap_pp must be 0) ================")
        print(growth_tree(book, res, by))
        print(f"\n---- contribution to total growth, by {by} ----")
        print(contribution(res, by))

In [57]:
#%run kalpa_clean.py
res, book = clean_all(df_results_2025_H1, df_results_2026_H1,
                      df_bookings_2025_H1, df_bookings_2026_H1)

bookings 2025: dropped 7 repeated header rows
  created_at: dd/mm/yyyy=436,302 | ISO=0 | unparsed=0
  slot_at: dd/mm/yyyy=436,302 | ISO=0 | unparsed=0
bookings 2026: dropped 8 repeated header rows
  created_at: dd/mm/yyyy=399,212 | ISO=62,439 | unparsed=0
  slot_at: dd/mm/yyyy=399,212 | ISO=62,439 | unparsed=0
results 2025: dropped 0 repeated header rows
  null test_code: 1,053 | recovered: 1,019 | still null: 34
  result_ts: dd/mm/yyyy=0 | ISO=357,769 | unparsed=0
results 2026: dropped 0 repeated header rows
  null test_code: 1,149 | recovered: 1,089 | still null: 60
  result_ts: dd/mm/yyyy=0 | ISO=378,358 | unparsed=0

================ QA REPORT ================
        rows  recovered  unknown  no_city
year
2025  357769       1019       34        0
2026  378358       1089       60        0

bookings rows with no patient_id (expect 0): 0

channel values (check for spelling variants between years):
year       2025    2026
channel
clinic   125170  108710
home      64707   87878
results with no booking (no channel): 3720

result months (expect mostly 1-6):
year        2025   2026
result_dt
1          58522  62437
2          59653  66423
3          60935  63901
4          59589  61979
5          58855  60460
6          58435  61243
7           1776   1911
12             4      4

results by city:
year         2025    2026  growth_pct
city
Ahmedabad   63152   70099        11.0
Bengaluru   81843   89129         8.9
Chennai     65603   66474         1.3
Hyderabad   60226   65021         8.0
Jaipur      37111   33439        -9.9
Pune        49834   54196         8.8
TOTAL      357769  378358         5.8

packages vs other tests:
year          2025    2026  growth_pct
is_package
False       313302  318248         1.6
True         44467   60110        35.2

bookings vs results (rescheduled duplicates removed from bookings):
           booked_growth  booked_excl_resched_growth  results_growth  \
city
Ahmedabad         10.605                      10.605          11.000
Bengaluru          7.586                       7.586           8.902
Chennai            3.605                       0.700           1.328
Hyderabad          7.424                       7.424           7.962
Jaipur            -8.091                     -10.771          -9.895
Pune               8.115                       8.115           8.753

           results_per_booked_2026
city
Ahmedabad                    0.824
Bengaluru                    0.828
Chennai                      0.822
Hyderabad                    0.826
Jaipur                       0.830
Pune                         0.826

================ GROWTH TREE: overall ================
overall                        ALL
patients                      3.76
visits_per_patient           -0.98
tests_per_visit               2.19
results_per_test_booked       0.72
product                       5.75
actual                        5.75
gap_pp                        0.00
results_2025             357769.00
results_2026             378358.00

================ GROWTH TREE by city (growth %, gap_pp must be 0) ================
           patients  visits_per_patient  tests_per_visit  results_per_test_booked  product  actual  gap_pp  results_2025  results_2026
city
Ahmedabad      9.70               -1.04             1.88                     0.36    11.00   11.00     0.0         63152         70099
Bengaluru      7.10               -2.26             2.78                     1.22     8.90    8.90     0.0         81843         89129
Chennai       -4.95                3.13             2.73                     0.62     1.33    1.33    -0.0         65603         66474
Hyderabad      8.10               -2.46             1.88                     0.50     7.96    7.96     0.0         60226         65021
Jaipur       -12.08               -0.24             1.73                     0.98    -9.89   -9.89    -0.0         37111         33439
Pune           8.84               -2.27             1.65                     0.59     8.75    8.75     0.0         49834         54196

---- contribution to total growth, by city ----
year         2025    2026  growth_pct  contribution_pp
city
Ahmedabad   63152   70099       11.00             1.94
Bengaluru   81843   89129        8.90             2.04
Chennai     65603   66474        1.33             0.24
Hyderabad   60226   65021        7.96             1.34
Jaipur      37111   33439       -9.89            -1.03
Pune        49834   54196        8.75             1.22
TOTAL      357769  378358        5.75             5.75

================ GROWTH TREE by channel (growth %, gap_pp must be 0) ================
         patients  visits_per_patient  tests_per_visit  results_per_test_booked  product  actual  gap_pp  results_2025  results_2026
channel
clinic      -8.28               -6.08             2.35                    -0.34   -12.14  -12.14    -0.0        228113        200428
home        26.25                6.83             1.89                     0.17    37.66   37.66    -0.0        127858        176008

---- contribution to total growth, by channel ----
year       2025    2026  growth_pct  contribution_pp
channel
clinic   228113  200428      -12.14            -7.74
home     127858  176008       37.66            13.46
NaN        1798    1922        6.90             0.03
TOTAL    357769  378358        5.75             5.75

================ GROWTH TREE by ['city', 'channel'] (growth %, gap_pp must be 0) ================
                   patients  visits_per_patient  tests_per_visit  results_per_test_booked  product  actual  gap_pp  results_2025  results_2026
city      channel
Ahmedabad clinic      -1.88               -6.00             2.01                    -0.68    -6.55   -6.55    -0.0         39969         37351
          home        31.19                6.55             1.52                    -0.13    41.72   41.72     0.0         22850         32383
Bengaluru clinic      -6.34               -6.74             2.92                     0.49    -9.66   -9.66     0.0         52188         47146
          home        30.49                6.13             2.45                     0.08    42.00   42.00     0.0         29258         41546
Chennai   clinic     -15.35               -3.11             2.85                    -0.43   -16.01  -16.01    -0.0         41999         35275
          home        18.71                8.95             2.46                     0.12    32.68   32.68    -0.0         23257         30858
Hyderabad clinic      -4.67               -7.63             2.25                    -0.53   -10.44  -10.44     0.0         38392         34382
          home        29.88                6.93             1.44                    -0.09    40.74   40.74     0.0         21530         30302
Jaipur    clinic     -21.69               -5.38             1.70                    -0.66   -25.15  -25.15     0.0         23766         17790
          home         6.95                6.48             1.74                     1.63    17.76   17.76    -0.0         13150         15485
Pune      clinic      -4.47               -7.32             1.81                    -0.62   -10.42  -10.42    -0.0         31799         28484
          home        32.78                5.98             1.40                     0.07    42.78   42.78     0.0         17813         25434

---- contribution to total growth, by ['city', 'channel'] ----
year                 2025    2026  growth_pct  contribution_pp
city      channel
Ahmedabad clinic    39969   37351       -6.55            -0.73
          home      22850   32383       41.72             2.66
          NaN         333     365        9.61             0.01
Bengaluru clinic    52188   47146       -9.66            -1.41
          home      29258   41546       42.00             3.43
          NaN         397     437       10.08             0.01
Chennai   clinic    41999   35275      -16.01            -1.88
          home      23257   30858       32.68             2.12
          NaN         347     341       -1.73            -0.00
Hyderabad clinic    38392   34382      -10.44            -1.12
          home      21530   30302       40.74             2.45
          NaN         304     337       10.86             0.01
Jaipur    clinic    23766   17790      -25.15            -1.67
          home      13150   15485       17.76             0.65
          NaN         195     164      -15.90            -0.01
Pune      clinic    31799   28484      -10.42            -0.93
          home      17813   25434       42.78             2.13
          NaN         222     278       25.23             0.02
TOTAL              357769  378358        5.75             5.75

In [58]:
import re
b = book.copy()
b['id_pattern'] = b['patient_id'].str.replace(r'\d', '9', regex=True).str.replace(r'[A-Z]', 'A', regex=True)
print(b.groupby(['city', 'year'])['id_pattern'].agg(lambda s: s.value_counts().head(3).to_dict()))

# returning patients: share of 2026 patients (per city) who also have a 2025 booking
p25 = set(b.loc[b.year == 2025, 'patient_id']);
r = b[b.year == 2026].drop_duplicates(['city', 'patient_id'])
print(r.assign(returning=r['patient_id'].isin(p25)).groupby('city')['returning'].mean().round(3))

city       year
Ahmedabad  2025     {'AAAA9999999': 76926}
           2026     {'AAAA9999999': 85084}
Bengaluru  2025    {'AAAA9999999': 100070}
           2026    {'AAAA9999999': 107661}
Chennai    2025     {'AAAA9999999': 80267}
           2026     {'AAAA9999999': 83161}
Hyderabad  2025     {'AAAA9999999': 73237}
           2026     {'AAAA9999999': 78674}
Jaipur     2025     {'AAAA9999999': 45149}
           2026     {'AAAA9999999': 41496}
Pune       2025     {'AAAA9999999': 60653}
           2026     {'AAAA9999999': 65575}
Name: id_pattern, dtype: object
city
Ahmedabad    0.298
Bengaluru    0.304
Chennai      0.358
Hyderabad    0.299
Jaipur       0.374
Pune         0.302
Name: returning, dtype: float64

In [59]:
pk = res[res['channel'].notna()].assign(is_pk=lambda d: d['test_code'].str.startswith('PK'))
x = pk.groupby(['channel', 'is_pk', 'year']).size().unstack('year')
x['growth_pct'] = (x[2026] / x[2025] - 1) * 100
print(x.round(1))

year             2025    2026  growth_pct
channel is_pk
clinic  False  199825  168569       -15.6
        True    28288   31859        12.6
home    False  111912  148061        32.3
        True    15946   27947        75.3

In [60]:
lo = df_bookings_jaipur_2026_06["status_at_export"]=="rescheduled"
display(df_bookings_jaipur_2026_06[lo])
w=(df_bookings_jaipur_2026_06["booking_id"]=="nova_jai_0052710")
df_bookings_jaipur_2026_06[w]

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient,tests,home_fee,rescheduled_from,status_at_export
24,nova_jai_0052733,2026-06-09 04:20:00+05:30,2026-06-11 07:14:00+05:30,Jaipur,JAI-03,CLINIC,APP,"{'patient_id': 'PJAI0009722', 'is_new': False}","[{'code': 'T006', 'price': 650}, {'code': 'T01...",0,None,rescheduled
37,nova_jai_0052746,2026-06-24 16:02:00+05:30,2026-06-29 17:57:00+05:30,Jaipur,JAI-01,CLINIC,APP,"{'patient_id': 'PJAI0025633', 'is_new': False}","[{'code': 'T007', 'price': 550}, {'code': 'T00...",0,None,rescheduled
52,nova_jai_0052761,2026-06-01 13:03:00+05:30,2026-06-03 16:23:00+05:30,Jaipur,JAI-03,CLINIC,WALKIN,"{'patient_id': 'PJAI0013857', 'is_new': False}","[{'code': 'T002', 'price': 120}, {'code': 'T00...",0,None,rescheduled
63,nova_jai_0052772,2026-06-15 22:27:00+05:30,2026-06-19 06:09:00+05:30,Jaipur,JAI-02,CLINIC,APP,"{'patient_id': 'PJAI0024265', 'is_new': False}","[{'code': 'T004', 'price': 650}, {'code': 'T01...",0,None,rescheduled
81,nova_jai_0052790,2026-06-07 02:29:00+05:30,2026-06-09 11:18:00+05:30,Jaipur,JAI-02,HOME,PHONE,"{'patient_id': 'PJAI0017296', 'is_new': False}","[{'code': 'T002', 'price': 120}, {'code': 'T00...",150,None,rescheduled
...,...,...,...,...,...,...,...,...,...,...,...,...
2771,nova_jai_0055480,2026-06-18 00:47:00+05:30,2026-06-18 07:04:00+05:30,Jaipur,JAI-04,CLINIC,APP,"{'patient_id': 'PJAI0029279', 'is_new': True}","[{'code': 'T003', 'price': 450}, {'code': 'PK0...",0,None,rescheduled
2792,nova_jai_0055501,2026-06-08 13:47:00+05:30,2026-06-12 16:47:00+05:30,Jaipur,JAI-01,HOME,APP,"{'patient_id': 'PJAI0029300', 'is_new': True}","[{'code': 'T006', 'price': 650}, {'code': 'T01...",150,None,rescheduled
2814,nova_jai_0055523,2026-06-27 01:20:00+05:30,2026-06-29 06:56:00+05:30,Jaipur,JAI-01,CLINIC,APP,"{'patient_id': 'PJAI0029322', 'is_new': True}","[{'code': 'T010', 'price': 150}]",0,None,rescheduled
2850,nova_jai_0055559,2026-06-21 11:05:00+05:30,2026-06-25 11:30:00+05:30,Jaipur,JAI-01,HOME,WALKIN,"{'patient_id': 'PJAI0029358', 'is_new': True}","[{'code': 'T020', 'price': 450}, {'code': 'PK0...",150,None,rescheduled
2856,nova_jai_0055565,2026-06-16 12:44:00+05:30,2026-06-20 19:20:00+05:30,Jaipur,JAI-02,HOME,PHONE,"{'patient_id': 'PJAI0029364', 'is_new': True}","[{'code': 'T002', 'price': 120}, {'code': 'T01...",150,None,rescheduled

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient,tests,home_fee,rescheduled_from,status_at_export
1,nova_jai_0052710,2026-06-05 02:57:00+05:30,2026-06-09 08:52:00+05:30,Jaipur,JAI-03,CLINIC,APP,"{'patient_id': 'PJAI0028823', 'is_new': False}","[{'code': 'T002', 'price': 120}, {'code': 'T01...",0,None,booked

In [61]:
df_results_jaipur_2026_06[df_results_jaipur_2026_06["booking_id"] == "nova_jai_0052710"]

         booking_id test_code            result_ts result_value result_flag
0  nova_jai_0052710      T002  2026-06-09 19:53:00   5.9 mmol/L      normal
1  nova_jai_0052710      T017  2026-06-09 15:53:00         62.1      normal

In [62]:
df_bookings_jaipur_2026_02

                booking_id        created_at           slot_at    city clinic_id channel  source   patient_id  patient_name test_code  test_price  home_fee
0     BK-JAI-202602-040954  18/02/2026 07:26  18/02/2026 09:03  Jaipur    JAI-03  clinic   phone  PJAI0025077    Zoya Menon      T002         120         0
1     BK-JAI-202602-040954  18/02/2026 07:26  18/02/2026 09:03  Jaipur    JAI-03  clinic   phone  PJAI0025077    Zoya Menon      T010         150         0
2     BK-JAI-202602-040954  18/02/2026 07:26  18/02/2026 09:03  Jaipur    JAI-03  clinic   phone  PJAI0025077    Zoya Menon      T006         650         0
3     BK-JAI-202602-040954  18/02/2026 07:26  18/02/2026 09:03  Jaipur    JAI-03  clinic   phone  PJAI0025077    Zoya Menon      T003         450         0
4     BK-JAI-202602-040954  18/02/2026 07:26  18/02/2026 09:03  Jaipur    JAI-03  clinic   phone  PJAI0025077    Zoya Menon      T017         450         0
...                    ...               ...               ...     ...       ...     ...     ...          ...           ...       ...         ...       ...
6800  BK-JAI-202602-043884  09/02/2026 06:05  12/02/2026 07:28  Jaipur    JAI-01  clinic     app  PJAI0027676   Arjun Singh      T002         120         0
6801  BK-JAI-202602-043885  10/02/2026 06:54  10/02/2026 08:10  Jaipur    JAI-03  clinic   phone  PJAI0027677    Ananya Rao      T004         650         0
6802  BK-JAI-202602-043886  06/02/2026 14:38  06/02/2026 17:35  Jaipur    JAI-04  clinic  walkin  PJAI0027678  Diya D'Souza      T005         700         0
6803  BK-JAI-202602-043886  06/02/2026 14:38  06/02/2026 17:35  Jaipur    JAI-04  clinic  walkin  PJAI0027678  Diya D'Souza      T002         120         0
6804  BK-JAI-202602-043886  06/02/2026 14:38  06/02/2026 17:35  Jaipur    JAI-04  clinic  walkin  PJAI0027678  Diya D'Souza      T011         750         0

[6805 rows x 12 columns]

In [63]:
(df_bookings_2026_H1.shape[0] - df_bookings_2025_H1.shape[0])*100/df_bookings_2025_H1.shape[0]

-2.4170943070163577

In [66]:
df_plan = pd.read_csv(data_dir/"datapack/plan/plan_2026_H1.csv")
df_plan

        city                   metric  2026-01  2026-02  2026-03  2026-04  2026-05  2026-06
0  Ahmedabad  test_volume_target_2026    15119    14814    14794    15608    15019    15419
1  Bangalore  test_volume_target_2026    20380    19877    21019    19271    19883    19655
2    Chennai  test_volume_target_2026    15474    15054    16536    15690    15512    15646
3  Hyderabad  test_volume_target_2026    14840    14790    14192    14905    14001    13693
4     Jaipur  test_volume_target_2026     8853     9369     9614     8014     8484     8038
5       Pune  test_volume_target_2026    12336    12389    11727    12128    11779    11818

In [ ]:
df_real =

In [67]:
import numpy as np, pandas as pd

MONTHS = ["2026-01","2026-02","2026-03","2026-04","2026-05","2026-06"]

def compare_plan(df_plan, res, book):
    """Plan vs actual by city and month, on two bases:
       results = result rows by result month; booked = booked test rows by slot month
       (rescheduled duplicate bookings removed)."""
    p = df_plan.copy()
    p["city"] = p["city"].str.strip().replace({"Bangalore": "Bengaluru"})
    plan = p.set_index("city")[MONTHS]

    r = res[res["year"] == 2026].copy()
    r["m"] = r["result_dt"].dt.strftime("%Y-%m")
    act_res = r[r["m"].isin(MONTHS)].groupby(["city", "m"]).size().unstack(fill_value=0).reindex(columns=MONTHS, fill_value=0)

    resched = book.loc[book["rescheduled_from"].notna(), "booking_id"].unique()
    b = book[(book["year"] == 2026) & ~book["booking_id"].isin(resched)].copy()
    b["m"] = b["slot_dt"].dt.strftime("%Y-%m")
    act_bk = b[b["m"].isin(MONTHS)].groupby(["city", "m"]).size().unstack(fill_value=0).reindex(columns=MONTHS, fill_value=0)

    def table(act, name):
        a = act.reindex(plan.index).fillna(0)
        t = pd.DataFrame({"plan": plan.sum(axis=1), name: a.sum(axis=1)})
        t.loc["TOTAL"] = t.sum()
        t["variance"] = t[name] - t["plan"]
        t["attainment_pct"] = (t[name] / t["plan"] * 100).round(1)
        mon = (a / plan * 100).round(1)
        mon.loc["TOTAL"] = (a.sum() / plan.sum() * 100).round(1)
        return t, mon
    return {"results": table(act_res, "actual_results"), "booked": table(act_bk, "actual_booked")}


def show_plan_comparison(df_plan, res, book):
    pd.set_option("display.width", 200)
    out = compare_plan(df_plan, res, book)
    for name, (tbl, monthly) in out.items():
        print(f"\n===== plan vs actual: {name} =====")
        print(tbl)
        print(f"\nattainment % by month ({name}):")
        print(monthly)
    return out

In [68]:
out = show_plan_comparison(df_plan, res, book)

===== plan vs actual: results =====
             plan  actual_results  variance  attainment_pct
city
Ahmedabad   90773           69737    -21036            76.8
Bengaluru  120085           88707    -31378            73.9
Chennai     93912           66108    -27804            70.4
Hyderabad   86421           64687    -21734            74.9
Jaipur      52372           33297    -19075            63.6
Pune        72177           53907    -18270            74.7
TOTAL      515740          376443   -139297            73.0

attainment % by month (results):
m          2026-01  2026-02  2026-03  2026-04  2026-05  2026-06
city
Ahmedabad     75.0     80.6     80.9     73.0     76.3     75.5
Bengaluru     72.0     82.1     69.3     76.1     73.3     70.7
Chennai       71.0     80.3     66.6     68.5     69.0     67.4
Hyderabad     71.4     77.2     77.5     72.5     72.3     78.4
Jaipur        62.0     61.2     59.3     66.7     64.1     69.6
Pune          75.7     72.0     82.4     74.4     69.3     74.6
TOTAL         71.8     77.0     72.7     72.4     71.4     72.7

===== plan vs actual: booked =====
             plan  actual_booked  variance  attainment_pct
city
Ahmedabad   90773          85084     -5689            93.7
Bengaluru  120085         107661    -12424            89.7
Chennai     93912          80829    -13083            86.1
Hyderabad   86421          78674     -7747            91.0
Jaipur      52372          40286    -12086            76.9
Pune        72177          65575     -6602            90.9
TOTAL      515740         458109    -57631            88.8

attainment % by month (booked):
m          2026-01  2026-02  2026-03  2026-04  2026-05  2026-06
city
Ahmedabad     92.6     98.2     97.0     89.3     93.0     92.6
Bengaluru     89.1     98.6     83.0     92.0     89.5     86.1
Chennai       88.5     97.7     80.7     83.2     84.9     82.3
Hyderabad     88.9     91.9     93.3     88.5     88.4     95.5
Jaipur        76.4     72.6     72.0     80.9     76.6     84.8
Pune          93.2     87.8     97.8     90.7     84.1     91.6
TOTAL         88.9     92.8     87.4     88.1     87.0     88.7